# See with https://github.com/google/mono_repo.dart for details on this file
sdk:
- 2.14.0
- dev

stages:
- smoke_test:
  - group:
    - format
    - analyze: --fatal-infos .
    sdk: [dev]
  - group:
    - analyze:
    sdk: [2.14.0]
- unit_test:
  - group:
    - test
