# See https://github.com/dart-lang/mono_repo for details
dart:
- 2.3.0-dev.0.3
- dev

stages:
- smoke_test:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
    dart: [dev]
  - group:
    - dartanalyzer: --fatal-warnings .
    dart: [2.3.0-dev.0.3]
- unit_test:
  - group:
    - test

cache:
  directories:
  - .dart_tool/build
