# See with https://github.com/google/mono_repo.dart for details on this file
sdk:
- pubspec
- dev

stages:
- smoke_test:
  - group:
    - format
    - analyze: --fatal-infos .
    sdk: [dev]
  - group:
    - analyze:
    sdk: [pubspec]
- unit_test:
  - test
