// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _9: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _129: x0 => x0.stopPropagation(),
      _130: x0 => x0.preventDefault(),
      _132: x0 => x0.remove(),
      _133: (x0,x1) => x0.append(x1),
      _134: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _179: x0 => x0.unlock(),
      _180: x0 => x0.getReader(),
      _181: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _182: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _183: (x0,x1) => x0.item(x1),
      _184: x0 => x0.next(),
      _185: x0 => x0.now(),
      _186: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._186(f,arguments.length,x0) }),
      _187: (x0,x1) => x0.addListener(x1),
      _188: (x0,x1) => x0.removeListener(x1),
      _189: (x0,x1) => x0.matchMedia(x1),
      _196: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._196(f,arguments.length,x0) }),
      _197: (x0,x1) => x0.getModifierState(x1),
      _198: (x0,x1) => x0.removeProperty(x1),
      _199: (x0,x1) => x0.prepend(x1),
      _200: x0 => new Intl.Locale(x0),
      _201: x0 => x0.disconnect(),
      _202: (x0,x1) => x0.observe(x1),
      _203: x0 => x0.disconnect(),
      _204: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._204(f,arguments.length,x0) }),
      _205: (x0,x1) => x0.getAttribute(x1),
      _206: (x0,x1) => x0.contains(x1),
      _207: (x0,x1) => x0.querySelector(x1),
      _208: x0 => x0.blur(),
      _209: x0 => x0.hasFocus(),
      _210: (x0,x1) => x0.removeAttribute(x1),
      _211: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _212: (x0,x1) => x0.hasAttribute(x1),
      _213: (x0,x1) => x0.getModifierState(x1),
      _214: (x0,x1) => x0.createTextNode(x1),
      _215: (x0,x1) => x0.appendChild(x1),
      _216: x0 => x0.getBoundingClientRect(),
      _217: (x0,x1) => x0.closest(x1),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _699: (x0,x1) => x0.warn(x1),
      _702: x0 => globalThis.parseFloat(x0),
      _703: () => globalThis.window,
      _704: () => globalThis.Intl,
      _705: () => globalThis.Symbol,
      _708: x0 => x0.clipboard,
      _709: x0 => x0.maxTouchPoints,
      _710: x0 => x0.vendor,
      _711: x0 => x0.language,
      _712: x0 => x0.platform,
      _713: x0 => x0.userAgent,
      _714: (x0,x1) => x0.vibrate(x1),
      _715: x0 => x0.languages,
      _716: x0 => x0.documentElement,
      _717: (x0,x1) => x0.querySelector(x1),
      _720: (x0,x1) => x0.createElement(x1),
      _723: (x0,x1) => x0.createEvent(x1),
      _724: x0 => x0.activeElement,
      _727: x0 => x0.head,
      _728: x0 => x0.body,
      _729: (x0,x1) => { x0.title = x1 },
      _733: x0 => x0.visibilityState,
      _734: () => globalThis.document,
      _735: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._735(f,arguments.length,x0) }),
      _736: (x0,x1) => x0.dispatchEvent(x1),
      _744: x0 => x0.target,
      _746: x0 => x0.timeStamp,
      _747: x0 => x0.type,
      _749: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _756: x0 => x0.firstChild,
      _760: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _763: x0 => x0.parentNode,
      _765: (x0,x1) => x0.removeChild(x1),
      _766: x0 => x0.isConnected,
      _774: x0 => x0.clientHeight,
      _775: x0 => x0.clientWidth,
      _776: x0 => x0.offsetHeight,
      _777: x0 => x0.offsetWidth,
      _778: x0 => x0.id,
      _779: (x0,x1) => { x0.id = x1 },
      _782: (x0,x1) => { x0.spellcheck = x1 },
      _783: x0 => x0.tagName,
      _784: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: x0 => x0.tabIndex,
      _789: (x0,x1) => { x0.tabIndex = x1 },
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _837: (x0,x1) => { x0.nonce = x1 },
      _842: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _958: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _1000: x0 => new MutationObserver(x0),
      _1001: (x0,x1,x2) => x0.observe(x1,x2),
      _1002: f => finalizeWrapper(f, function(x0,x1) { return dartInstance.exports._1002(f,arguments.length,x0,x1) }),
      _1005: x0 => x0.attributeName,
      _1006: x0 => x0.type,
      _1007: x0 => x0.matches,
      _1008: x0 => x0.matches,
      _1012: x0 => x0.relatedTarget,
      _1014: x0 => x0.clientX,
      _1015: x0 => x0.clientY,
      _1016: x0 => x0.offsetX,
      _1017: x0 => x0.offsetY,
      _1020: x0 => x0.button,
      _1021: x0 => x0.buttons,
      _1022: x0 => x0.ctrlKey,
      _1026: x0 => x0.pointerId,
      _1027: x0 => x0.pointerType,
      _1028: x0 => x0.pressure,
      _1029: x0 => x0.tiltX,
      _1030: x0 => x0.tiltY,
      _1031: x0 => x0.getCoalescedEvents(),
      _1034: x0 => x0.deltaX,
      _1035: x0 => x0.deltaY,
      _1036: x0 => x0.wheelDeltaX,
      _1037: x0 => x0.wheelDeltaY,
      _1038: x0 => x0.deltaMode,
      _1045: x0 => x0.changedTouches,
      _1048: x0 => x0.clientX,
      _1049: x0 => x0.clientY,
      _1052: x0 => x0.data,
      _1054: (x0,x1) => { x0.disabled = x1 },
      _1057: (x0,x1) => { x0.type = x1 },
      _1058: (x0,x1) => { x0.max = x1 },
      _1059: (x0,x1) => { x0.min = x1 },
      _1060: (x0,x1) => { x0.value = x1 },
      _1061: x0 => x0.value,
      _1062: x0 => x0.disabled,
      _1063: (x0,x1) => { x0.disabled = x1 },
      _1065: (x0,x1) => { x0.placeholder = x1 },
      _1067: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1070: x0 => x0.selectionDirection,
      _1071: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1076: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1077: (x0,x1) => x0.add(x1),
      _1080: (x0,x1) => { x0.noValidate = x1 },
      _1081: (x0,x1) => { x0.method = x1 },
      _1082: (x0,x1) => { x0.action = x1 },
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: f => finalizeWrapper(f, function(x0,x1) { return dartInstance.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1192: x0 => x0.hostElement,
      _1193: x0 => x0.viewConstraints,
      _1196: x0 => x0.maxHeight,
      _1197: x0 => x0.maxWidth,
      _1198: x0 => x0.minHeight,
      _1199: x0 => x0.minWidth,
      _1200: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._1200(f,arguments.length,x0) }),
      _1201: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._1201(f,arguments.length,x0) }),
      _1202: (x0,x1) => ({addView: x0,removeView: x1}),
      _1205: x0 => x0.loader,
      _1206: () => globalThis._flutter,
      _1207: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1208: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._1208(f,arguments.length,x0) }),
      _1209: f => finalizeWrapper(f, function() { return dartInstance.exports._1209(f,arguments.length) }),
      _1210: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1213: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._1213(f,arguments.length,x0) }),
      _1214: x0 => ({runApp: x0}),
      _1216: (x0,x1,x2) => x0.call(x1,x2),
      _1217: f => finalizeWrapper(f, function(x0,x1) { return dartInstance.exports._1217(f,arguments.length,x0,x1) }),
      _1218: x0 => new Promise(x0),
      _1219: x0 => x0.length,
      _1292: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1312: Date.now,
      _1314: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1315: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1316: () => {
        let stackString = new Error().stack.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1317: () => typeof dartUseDateNowForTicks !== "undefined",
      _1318: () => 1000 * performance.now(),
      _1319: () => Date.now(),
      _1322: () => new WeakMap(),
      _1323: (map, o) => map.get(o),
      _1324: (map, o, v) => map.set(o, v),
      _1325: x0 => new WeakRef(x0),
      _1326: x0 => x0.deref(),
      _1333: () => globalThis.WeakRef,
      _1337: s => JSON.stringify(s),
      _1338: s => printToConsole(s),
      _1339: (o, p, r) => o.replaceAll(p, () => r),
      _1341: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1342: s => s.toUpperCase(),
      _1343: s => s.trim(),
      _1344: s => s.trimLeft(),
      _1345: s => s.trimRight(),
      _1346: (string, times) => string.repeat(times),
      _1347: Function.prototype.call.bind(String.prototype.indexOf),
      _1348: (s, p, i) => s.lastIndexOf(p, i),
      _1349: (string, token) => string.split(token),
      _1350: Object.is,
      _1354: (o, c) => o instanceof c,
      _1355: o => Object.keys(o),
      _1385: x0 => new Array(x0),
      _1387: x0 => x0.length,
      _1389: (x0,x1) => x0[x1],
      _1390: (x0,x1,x2) => { x0[x1] = x2 },
      _1393: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1395: x0 => new Int8Array(x0),
      _1396: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1398: x0 => new Uint8ClampedArray(x0),
      _1400: x0 => new Int16Array(x0),
      _1402: x0 => new Uint16Array(x0),
      _1404: x0 => new Int32Array(x0),
      _1406: x0 => new Uint32Array(x0),
      _1408: x0 => new Float32Array(x0),
      _1410: x0 => new Float64Array(x0),
      _1416: x0 => x0.random(),
      _1419: () => globalThis.Math,
      _1432: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1433: (handle) => clearTimeout(handle),
      _1434: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1435: (handle) => clearInterval(handle),
      _1436: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1437: () => Date.now(),
      _1438: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1439: (x0,x1) => x0.exec(x1),
      _1440: (x0,x1) => x0.test(x1),
      _1441: x0 => x0.pop(),
      _1443: o => o === undefined,
      _1445: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1447: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1448: o => o instanceof RegExp,
      _1449: (l, r) => l === r,
      _1450: o => o,
      _1451: o => o,
      _1452: o => o,
      _1453: b => !!b,
      _1454: o => o.length,
      _1456: (o, i) => o[i],
      _1457: f => f.dartFunction,
      _1458: () => ({}),
      _1459: () => [],
      _1461: () => globalThis,
      _1462: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1464: (o, p) => o[p],
      _1465: (o, p, v) => o[p] = v,
      _1466: (o, m, a) => o[m].apply(o, a),
      _1468: o => String(o),
      _1469: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1470: f => finalizeWrapper(f, function(x0) { return dartInstance.exports._1470(f,arguments.length,x0) }),
      _1471: f => finalizeWrapper(f, function(x0,x1) { return dartInstance.exports._1471(f,arguments.length,x0,x1) }),
      _1472: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1473: o => [o],
      _1474: (o0, o1) => [o0, o1],
      _1475: (o0, o1, o2) => [o0, o1, o2],
      _1476: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1477: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1478: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1481: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1482: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1483: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1484: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1485: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1486: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1487: x0 => new ArrayBuffer(x0),
      _1488: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1490: x0 => x0.index,
      _1492: x0 => x0.flags,
      _1493: x0 => x0.multiline,
      _1494: x0 => x0.ignoreCase,
      _1495: x0 => x0.unicode,
      _1496: x0 => x0.dotAll,
      _1497: (x0,x1) => { x0.lastIndex = x1 },
      _1498: (o, p) => p in o,
      _1499: (o, p) => o[p],
      _1516: o => o instanceof Array,
      _1517: (a, i) => a.push(i),
      _1521: a => a.pop(),
      _1522: (a, i) => a.splice(i, 1),
      _1524: (a, s, e) => a.slice(s, e),
      _1526: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _1527: a => a.length,
      _1529: (a, i) => a[i],
      _1530: (a, i, v) => a[i] = v,
      _1532: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _1533: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _1535: o => o instanceof Uint8Array,
      _1536: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _1537: o => o instanceof Int8Array,
      _1538: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _1539: o => o instanceof Uint8ClampedArray,
      _1540: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _1541: o => o instanceof Uint16Array,
      _1542: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _1543: o => o instanceof Int16Array,
      _1544: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _1545: o => o instanceof Uint32Array,
      _1546: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _1547: o => o instanceof Int32Array,
      _1548: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _1550: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _1551: o => o instanceof Float32Array,
      _1552: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _1553: o => o instanceof Float64Array,
      _1554: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _1555: (t, s) => t.set(s),
      _1557: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _1559: o => o.buffer,
      _1560: o => o.byteOffset,
      _1561: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _1562: (b, o) => new DataView(b, o),
      _1563: (b, o, l) => new DataView(b, o, l),
      _1564: Function.prototype.call.bind(DataView.prototype.getUint8),
      _1565: Function.prototype.call.bind(DataView.prototype.setUint8),
      _1566: Function.prototype.call.bind(DataView.prototype.getInt8),
      _1567: Function.prototype.call.bind(DataView.prototype.setInt8),
      _1568: Function.prototype.call.bind(DataView.prototype.getUint16),
      _1569: Function.prototype.call.bind(DataView.prototype.setUint16),
      _1570: Function.prototype.call.bind(DataView.prototype.getInt16),
      _1571: Function.prototype.call.bind(DataView.prototype.setInt16),
      _1572: Function.prototype.call.bind(DataView.prototype.getUint32),
      _1573: Function.prototype.call.bind(DataView.prototype.setUint32),
      _1574: Function.prototype.call.bind(DataView.prototype.getInt32),
      _1575: Function.prototype.call.bind(DataView.prototype.setInt32),
      _1578: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _1579: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _1580: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _1581: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _1582: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _1583: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _1584: Function.prototype.call.bind(Number.prototype.toString),
      _1585: Function.prototype.call.bind(BigInt.prototype.toString),
      _1586: Function.prototype.call.bind(Number.prototype.toString),
      _1587: (d, digits) => d.toFixed(digits),
      _3435: () => globalThis.window,
      _3497: x0 => x0.navigator,
      _3886: x0 => x0.userAgent,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
