#!/bin/bash
PACK_DIR=`pwd`/packages/
cmd="dart
--enable_type_checks
--enable_asserts
--verbose_debug
--warning_as_error
--error_on_malformed_type
--package-root=$PACK_DIR
./test/console_test_harness.dart"
echo $cmd
exec $cmd
