
var skwasm = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(skwasm) {
  skwasm = skwasm || {};


function e(){h.buffer!=l&&q(h.buffer);return aa}function r(){h.buffer!=l&&q(h.buffer);return ba}function u(){h.buffer!=l&&q(h.buffer);return ca}function da(){h.buffer!=l&&q(h.buffer);return ea}function w(){h.buffer!=l&&q(h.buffer);return ha}function ia(){h.buffer!=l&&q(h.buffer);return ja}null;var y;y||(y=typeof skwasm !== 'undefined' ? skwasm : {});var ka=Object.assign,la,ma;y.ready=new Promise(function(a,b){la=a;ma=b});
var na=ka({},y),oa="./this.program",pa=(a,b)=>{throw b;},qa="object"===typeof window,z="function"===typeof importScripts,A="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,B=y.ENVIRONMENT_IS_PTHREAD||!1,C="";function ra(a){return y.locateFile?y.locateFile(a,C):C+a}var sa,ta,ua,fs,va,wa;
if(A){C=z?require("path").dirname(C)+"/":__dirname+"/";wa=()=>{va||(fs=require("fs"),va=require("path"))};sa=function(b,c){wa();b=va.normalize(b);return fs.readFileSync(b,c?null:"utf8")};ua=b=>{b=sa(b,!0);b.buffer||(b=new Uint8Array(b));return b};ta=(b,c,d)=>{wa();b=va.normalize(b);fs.readFile(b,function(f,g){f?d(f):c(g.buffer)})};1<process.argv.length&&(oa=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);process.on("uncaughtException",function(b){if(!(b instanceof xa))throw b;});process.on("unhandledRejection",
function(b){throw b;});pa=(b,c)=>{if(ya())throw process.exitCode=b,c;c instanceof xa||E("exiting due to exception: "+c);process.exit(b)};y.inspect=function(){return"[Emscripten Module object]"};let a;try{a=require("worker_threads")}catch(b){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),b;}global.Worker=a.Worker}else if(qa||z)z?C=self.location.href:"undefined"!==typeof document&&document.currentScript&&(C=document.currentScript.src),
_scriptDir&&(C=_scriptDir),0!==C.indexOf("blob:")?C=C.substr(0,C.replace(/[?#].*/,"").lastIndexOf("/")+1):C="",A||(sa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},z&&(ua=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ta=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=
c;d.send(null)});A&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);var za=console.log.bind(console),Aa=console.warn.bind(console);A&&(wa(),za=a=>fs.writeSync(1,a+"\n"),Aa=a=>fs.writeSync(2,a+"\n"));var Ba=y.print||za,E=y.printErr||Aa;ka(y,na);na=null;y.thisProgram&&(oa=y.thisProgram);y.quit&&(pa=y.quit);var Ca,Da=[],F,Ea=0,Fa;y.wasmBinary&&(Fa=y.wasmBinary);var noExitRuntime=y.noExitRuntime||!0;"object"!==typeof WebAssembly&&Ga("no native wasm support detected");
var h,Ha,Ia=!1;function Ja(a){var b=new TextDecoder(a);this.decode=c=>{c.buffer instanceof SharedArrayBuffer&&(c=new Uint8Array(c));return b.decode.call(b,c)}}var Ka="undefined"!==typeof TextDecoder?new Ja("utf8"):void 0;
function La(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ka)return Ka.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function H(a,b){return a?La(r(),a,b):""}
function Ma(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var n=a.charCodeAt(++g);k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}function Na(a,b,c){return Ma(a,r(),b,c)}
function Oa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new Ja("utf-16le");function Pa(a,b){e().set(a,b)}var l,aa,ba,Qa,Ra,ca,ea,ha,ja;B&&(l=y.buffer);
function q(a){l=a;y.HEAP8=aa=new Int8Array(a);y.HEAP16=Qa=new Int16Array(a);y.HEAP32=ca=new Int32Array(a);y.HEAPU8=ba=new Uint8Array(a);y.HEAPU16=Ra=new Uint16Array(a);y.HEAPU32=ea=new Uint32Array(a);y.HEAPF32=ha=new Float32Array(a);y.HEAPF64=ja=new Float64Array(a)}var Sa=y.INITIAL_MEMORY||16777216;
if(B)h=y.wasmMemory,l=y.buffer;else if(y.wasmMemory)h=y.wasmMemory;else if(h=new WebAssembly.Memory({initial:Sa/65536,maximum:32768,shared:!0}),!(h.buffer instanceof SharedArrayBuffer))throw E("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),A&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");h&&(l=h.buffer);Sa=l.byteLength;q(l);var Ta,Ua=[],Va=[],Wa=[],Xa=0;function ya(){return noExitRuntime||0<Xa}function Ya(){var a=y.preRun.shift();Ua.unshift(a)}var Za=0,$a=null,ab=null;y.preloadedImages={};y.preloadedAudios={};function Ga(a){if(B)postMessage({cmd:"onAbort",arg:a});else if(y.onAbort)y.onAbort(a);a="Aborted("+a+")";E(a);Ia=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");ma(a);throw a;}
function bb(){return I.startsWith("data:application/octet-stream;base64,")}var I;I="skwasm.wasm";bb()||(I=ra(I));function cb(){var a=I;try{if(a==I&&Fa)return new Uint8Array(Fa);if(ua)return ua(a);throw"both async and sync fetching of the wasm failed";}catch(b){Ga(b)}}
function db(){if(!Fa&&(qa||z)){if("function"===typeof fetch&&!I.startsWith("file://"))return fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return cb()});if(ta)return new Promise(function(a,b){ta(I,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return cb()})}var eb={};
function fb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(y);else{var c=b.Oa;"number"===typeof c?void 0===b.C?J(c)():J(c)(b.C):c(void 0===b.C?null:b.C)}}}function gb(a){var b=K();a=a();L(b);return a}function hb(a){var b=M.l[a];b&&(u()[a>>2]=0,M.ga(b.worker))}
var M={m:[],G:[],W:[],ua:function(){for(var a=0;1>a;++a)M.Y()},va:function(){M.receiveObjectTransfer=M.ya;M.threadInit=M.ia;M.setExitStatus=M.Aa},l:{},Aa:function(){},ha:function(){for(var a in M.l){var b=M.l[a];b&&b.worker&&M.ga(b.worker)}for(a=0;a<M.m.length;++a)M.m[a].terminate();M.m=[]},ga:function(a){M.za(function(){delete M.l[a.v.V];M.m.push(a);M.G.splice(M.G.indexOf(a),1);ib(a.v.V);a.v=void 0})},za:function(a){u()[jb>>2]=0;try{a()}finally{u()[jb>>2]=1}},ya:function(a){if("undefined"!==typeof kb){for(var b in a.O)N[b]=
a.O[b];!y.canvas&&a.u&&N[a.u]&&(y.canvas=N[a.u].o,y.canvas.id=a.u)}},ia:function(){for(var a in M.W)M.W[a]()},da:function(a,b){a.onmessage=c=>{c=c.data;var d=c.cmd;a.v&&(M.na=a.v.V);if(c.targetThread&&c.targetThread!=lb()){var f=M.l[c.Va];f?f.worker.postMessage(c,c.transferList):E('Internal error! Worker sent a message "'+d+'" to target pthread '+c.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===d)mb();else if("spawnThread"===d)nb(c);else if("cleanupThread"===
d)hb(c.thread);else if("killThread"===d)c=c.thread,u()[c>>2]=0,d=M.l[c],delete M.l[c],d.worker.terminate(),ib(c),M.G.splice(M.G.indexOf(d.worker),1),d.worker.v=void 0;else if("cancelThread"===d)M.l[c.thread].worker.postMessage({cmd:"cancel"});else if("loaded"===d)a.loaded=!0,b&&b(a),a.F&&(a.F(),delete a.F);else if("print"===d)Ba("Thread "+c.threadId+": "+c.text);else if("printErr"===d)E("Thread "+c.threadId+": "+c.text);else if("alert"===d)alert("Thread "+c.threadId+": "+c.text);else if("setimmediate"===
c.target)a.postMessage(c);else if("onAbort"===d){if(y.onAbort)y.onAbort(c.arg)}else E("worker sent an unknown command "+d);M.na=void 0};a.onerror=c=>{E("worker sent an error! "+c.filename+":"+c.lineno+": "+c.message);throw c;};A&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("detachedExit",function(){}));a.postMessage({cmd:"load",urlOrBlob:y.mainScriptUrlOrBlob||_scriptDir,wasmMemory:h,wasmModule:Ha})},Y:function(){var a=ra("skwasm.worker.js");M.m.push(new Worker(a))},
qa:function(){0==M.m.length&&(M.Y(),M.da(M.m[0]));return M.m.pop()}};y.establishStackSpace=function(){var a=lb(),b=u()[a+44>>2];a=u()[a+48>>2];ob(b,b-a);L(b)};function pb(a){if(B)return O(1,0,a);try{qb(a)}catch(b){b instanceof xa||"unwind"==b||pa(1,b)}}function J(a){return Ta.get(a)}y.invokeEntryPoint=function(a,b){return J(a)(b)};var rb;rb=A?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:B?()=>performance.now()-y.__performance_now_clock_drift:()=>performance.now();
function sb(a){this.D=a-16;this.Fa=function(b){u()[this.D+4>>2]=b};this.Ca=function(b){u()[this.D+8>>2]=b};this.Da=function(){u()[this.D>>2]=0};this.Ba=function(){var b=0;e()[this.D+12>>0]=b};this.Ea=function(){var b=0;e()[this.D+13>>0]=b};this.sa=function(b,c){this.Fa(b);this.Ca(c);this.Da();this.Ba();this.Ea()}}var tb=0;
function nb(a){var b=M.qa();if(!b)return 6;M.G.push(b);var c=M.l[a.U]={worker:b,V:a.U};b.v=c;var d={cmd:"run",start_routine:a.Ga,arg:a.C,threadInfoStruct:a.U};d.u=a.u;d.O=a.O;b.F=()=>{d.time=performance.now();b.postMessage(d,a.La)};b.loaded&&(b.F(),delete b.F);return 0}var ub={},vb=[null,[],[]],wb={};function xb(a,b,c){return B?O(2,1,a,b,c):0}function yb(a,b){if(B)return O(3,1,a,b)}function zb(a,b,c){return B?O(4,1,a,b,c):0}
function Ab(a,b,c,d,f,g){if(B)b=O(5,1,a,b,c,d,f,g);else if(g<<=12,0!==(d&16)&&0!==a%65536)b=-28;else if(0!==(d&32)){var k=65536*Math.ceil(b/65536);(a=Bb(65536,k))?r().fill(0,a,a+k):a=0;a?(ub[a]={xa:a,wa:b,la:!0,fd:f,Sa:c,flags:d,offset:g},b=a):b=-48}else b=-52;return b}function Cb(a,b){if(B)a=O(6,1,a,b);else{var c=ub[a];0!==b&&c?(b===c.wa&&(ub[a]=null,c.la&&Db(c.xa)),a=0):a=-28}return a}function Eb(a,b,c){if(B)return O(7,1,a,b,c)}
function Fb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,k){b.drawElementsInstancedANGLE(c,d,f,g,k)})}
function Gb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Hb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var Ib=1,Jb=[],P=[],Kb=[],Lb=[],Mb=[],Q=[],R=[],Nb={},N={},Ob=[],Pb=[],Qb={},Rb={},Sb=4;function S(a){Tb||(Tb=a)}function Ub(a){for(var b=Ib++,c=a.length;c<b;c++)a[c]=null;return b}function Vb(a,b){a.ba||(a.ba=a.getContext,a.getContext=function(d,f){f=a.ba(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=1<b.ea?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Wb(c,b):0}
function Wb(a,b){var c=Xb(8);u()[c+4>>2]=lb();var d={Pa:c,attributes:b,version:b.ea,B:a};a.canvas&&(a.canvas.J=d);Nb[c]=d;("undefined"===typeof b.aa||b.aa)&&Yb(d);return c}
function Yb(a){a||(a=T);if(!a.ta){a.ta=!0;var b=a.B;Fb(b);Gb(b);Hb(b);b.Z=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.fa=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.$=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.$)b.$=b.getExtension("EXT_disjoint_timer_query");b.Ra=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var kb={},Tb,T,Zb=[];function $b(a,b,c,d){for(var f=0;f<a;f++){var g=U[c](),k=g&&Ub(d);g?(g.name=k,d[k]=g):S(1282);u()[b+4*f>>2]=k}}
function ac(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&S(1280);return;case 34814:case 36345:d=0;break;case 34466:var f=U.getParameter(34467);d=f?f.length:0;break;case 33309:if(2>T.version){S(1282);return}d=2*(U.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>T.version){S(1280);return}d=33307==a?3:0}if(void 0===d)switch(f=U.getParameter(a),typeof f){case "number":d=f;break;case "boolean":d=f?1:0;break;case "string":S(1280);return;case "object":if(null===
f)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:S(1280);return}else{if(f instanceof Float32Array||f instanceof Uint32Array||f instanceof Int32Array||f instanceof Array){for(a=0;a<f.length;++a)switch(c){case 0:u()[b+4*a>>2]=f[a];break;case 2:w()[b+4*a>>2]=f[a];break;case 4:e()[b+a>>0]=f[a]?1:0}return}try{d=f.name|
0}catch(g){S(1280);E("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:S(1280);E("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+f+" of type "+typeof f+"!");return}switch(c){case 1:c=d;da()[b>>2]=c;da()[b+4>>2]=(c-da()[b>>2])/4294967296;break;case 0:u()[b>>2]=d;break;case 2:w()[b>>2]=d;break;case 4:e()[b>>0]=d?1:0}}else S(1281)}
function bc(a){var b=Oa(a)+1,c=Xb(b);Na(a,c,b);return c}function cc(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function dc(a){a-=5120;0==a?a=e():1==a?a=r():2==a?(h.buffer!=l&&q(h.buffer),a=Qa):4==a?a=u():6==a?a=w():5==a||28922==a||28520==a||30779==a||30782==a?a=da():(h.buffer!=l&&q(h.buffer),a=Ra);return a}
function ec(a,b,c,d,f){a=dc(a);var g=31-Math.clz32(a.BYTES_PER_ELEMENT),k=Sb;return a.subarray(f>>g,f+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<g)+k-1&-k)>>g)}function V(a){var b=U.ma;if(b){var c=b.I[a];"number"===typeof c&&(b.I[a]=c=U.getUniformLocation(b,b.ja[a]+(0<c?"["+c+"]":"")));return c}S(1282)}var W=[],fc=[];
function O(a,b){var c=arguments.length-2,d=arguments;return gb(function(){for(var f=gc(8*c),g=f>>3,k=0;k<c;k++){var n=d[2+k];ia()[g+k]=n}return hc(a,c,f,b)})}var ic=[];function jc(a,b,c,d){gb(function(){var f=gc(12),g=0;b&&(g=bc(b));u()[f>>2]=g;u()[f+4>>2]=c;u()[f+8>>2]=d;kc(a,657457152,0,g,f)})}function lc(a){a=2<a?H(a):a;return N[a.substr(1)]||"canvas"==a&&Object.keys(N)[0]||"undefined"!==typeof document&&document.querySelector(a)}
function mc(a,b,c){var d=lc(a);if(!d)return-4;d.g&&(u()[d.g>>2]=b,u()[d.g+4>>2]=c);if(d.o||!d.K)d.o&&(d=d.o),a=!1,d.J&&d.J.B&&(a=d.J.B.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.J.B.viewport(0,0,b,c);else return d.g?(d=u()[d.g+8>>2],a=a?H(a):"",jc(d,a,b,c),1):-4;return 0}function nc(a,b,c){return B?O(8,1,a,b,c):mc(a,b,c)}var oc=["default","low-power","high-performance"];
function pc(a,b){b>>=2;var c=u()[b+6];b={alpha:!!u()[b],depth:!!u()[b+1],stencil:!!u()[b+2],antialias:!!u()[b+3],premultipliedAlpha:!!u()[b+4],preserveDrawingBuffer:!!u()[b+5],powerPreference:oc[c],failIfMajorPerformanceCaveat:!!u()[b+7],ea:u()[b+8],Qa:u()[b+9],aa:u()[b+10],pa:u()[b+11],Ta:u()[b+12],Ua:u()[b+13]};a=lc(a);if(!a)return 0;a.o&&(a=a.o);if(b.pa){if(!(a.transferControlToOffscreen||"undefined"!==typeof OffscreenCanvas&&a instanceof OffscreenCanvas))return 0;if(a.transferControlToOffscreen){if(!a.K)N[a.id]=
{canvas:a.transferControlToOffscreen(),g:Xb(12),id:a.id},a.K=!0;else if(!N[a.id])return 0;a=N[a.id]}}return Vb(a,b)}var rc={};function sc(){if(!tc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:oa||"./this.program"},b;for(b in rc)void 0===rc[b]?delete a[b]:a[b]=rc[b];var c=[];for(b in a)c.push(b+"="+a[b]);tc=c}return tc}var tc;
function uc(a,b){if(B)return O(9,1,a,b);var c=0;sc().forEach(function(d,f){var g=b+c;f=u()[a+4*f>>2]=g;for(g=0;g<d.length;++g)e()[f++>>0]=d.charCodeAt(g);e()[f>>0]=0;c+=d.length+1});return 0}function vc(a,b){if(B)return O(10,1,a,b);var c=sc();u()[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});u()[b>>2]=d;return 0}function wc(a){return B?O(11,1,a):0}function xc(a,b,c,d,f,g){if(B)return O(12,1,a,b,c,d,f,g);a=wb.ra(a);b=wb.oa(a,b,c,d);u()[g>>2]=b;return 0}
function yc(a,b,c,d){if(B)return O(13,1,a,b,c,d);a=wb.ra(a);b=wb.oa(a,b,c);u()[d>>2]=b;return 0}function zc(a,b,c,d,f){if(B)return O(14,1,a,b,c,d,f)}function Ac(a,b,c,d){if(B)return O(15,1,a,b,c,d);for(var f=0,g=0;g<c;g++){var k=u()[b>>2],n=u()[b+4>>2];b+=8;for(var p=0;p<n;p++){var t=r()[k+p],v=vb[a];0===t||10===t?((1===a?Ba:E)(La(v,0)),v.length=0):v.push(t)}f+=n}u()[d>>2]=f;return 0}function Bc(a){return 0===a%4&&(0!==a%100||0===a%400)}function Cc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Dc=[31,29,31,30,31,30,31,31,30,31,30,31],Ec=[31,28,31,30,31,30,31,31,30,31,30,31];function Fc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Bc(a.getFullYear())?Dc:Ec)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Gc(a,b,c,d){function f(m,x,D){for(m="number"===typeof m?m.toString():m||"";m.length<x;)m=D[0]+m;return m}function g(m,x){return f(m,x,"0")}function k(m,x){function D(qc){return 0>qc?-1:0<qc?1:0}var fa;0===(fa=D(m.getFullYear()-x.getFullYear()))&&0===(fa=D(m.getMonth()-x.getMonth()))&&(fa=D(m.getDate()-x.getDate()));return fa}function n(m){switch(m.getDay()){case 0:return new Date(m.getFullYear()-1,11,29);case 1:return m;case 2:return new Date(m.getFullYear(),0,3);case 3:return new Date(m.getFullYear(),
0,2);case 4:return new Date(m.getFullYear(),0,1);case 5:return new Date(m.getFullYear()-1,11,31);case 6:return new Date(m.getFullYear()-1,11,30)}}function p(m){m=Fc(new Date(m.h+1900,0,1),m.S);var x=new Date(m.getFullYear()+1,0,4),D=n(new Date(m.getFullYear(),0,4));x=n(x);return 0>=k(D,m)?0>=k(x,m)?m.getFullYear()+1:m.getFullYear():m.getFullYear()-1}var t=u()[d+40>>2];d={Ja:u()[d>>2],Ia:u()[d+4>>2],P:u()[d+8>>2],H:u()[d+12>>2],A:u()[d+16>>2],h:u()[d+20>>2],R:u()[d+24>>2],S:u()[d+28>>2],Wa:u()[d+32>>
2],Ha:u()[d+36>>2],Ka:t?H(t):""};c=H(c);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var v in t)c=c.replace(new RegExp(v,"g"),t[v]);var Y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
G="January February March April May June July August September October November December".split(" ");t={"%a":function(m){return Y[m.R].substring(0,3)},"%A":function(m){return Y[m.R]},"%b":function(m){return G[m.A].substring(0,3)},"%B":function(m){return G[m.A]},"%C":function(m){return g((m.h+1900)/100|0,2)},"%d":function(m){return g(m.H,2)},"%e":function(m){return f(m.H,2," ")},"%g":function(m){return p(m).toString().substring(2)},"%G":function(m){return p(m)},"%H":function(m){return g(m.P,2)},"%I":function(m){m=
m.P;0==m?m=12:12<m&&(m-=12);return g(m,2)},"%j":function(m){return g(m.H+Cc(Bc(m.h+1900)?Dc:Ec,m.A-1),3)},"%m":function(m){return g(m.A+1,2)},"%M":function(m){return g(m.Ia,2)},"%n":function(){return"\n"},"%p":function(m){return 0<=m.P&&12>m.P?"AM":"PM"},"%S":function(m){return g(m.Ja,2)},"%t":function(){return"\t"},"%u":function(m){return m.R||7},"%U":function(m){var x=new Date(m.h+1900,0,1),D=0===x.getDay()?x:Fc(x,7-x.getDay());m=new Date(m.h+1900,m.A,m.H);return 0>k(D,m)?g(Math.ceil((31-D.getDate()+
(Cc(Bc(m.getFullYear())?Dc:Ec,m.getMonth()-1)-31)+m.getDate())/7),2):0===k(D,x)?"01":"00"},"%V":function(m){var x=new Date(m.h+1901,0,4),D=n(new Date(m.h+1900,0,4));x=n(x);var fa=Fc(new Date(m.h+1900,0,1),m.S);return 0>k(fa,D)?"53":0>=k(x,fa)?"01":g(Math.ceil((D.getFullYear()<m.h+1900?m.S+32-D.getDate():m.S+1-D.getDate())/7),2)},"%w":function(m){return m.R},"%W":function(m){var x=new Date(m.h,0,1),D=1===x.getDay()?x:Fc(x,0===x.getDay()?1:7-x.getDay()+1);m=new Date(m.h+1900,m.A,m.H);return 0>k(D,m)?
g(Math.ceil((31-D.getDate()+(Cc(Bc(m.getFullYear())?Dc:Ec,m.getMonth()-1)-31)+m.getDate())/7),2):0===k(D,x)?"01":"00"},"%y":function(m){return(m.h+1900).toString().substring(2)},"%Y":function(m){return m.h+1900},"%z":function(m){m=m.Ha;var x=0<=m;m=Math.abs(m)/60;return(x?"+":"-")+String("0000"+(m/60*100+m%60)).slice(-4)},"%Z":function(m){return m.Ka},"%%":function(){return"%"}};for(v in t)c.includes(v)&&(c=c.replace(new RegExp(v,"g"),t[v](d)));v=Hc(c);if(v.length>b)return 0;Pa(v,a);return v.length-
1}B||M.ua();for(var U,X=0;32>X;++X)Zb.push(Array(X));var Ic=new Float32Array(288);for(X=0;288>X;++X)W[X]=Ic.subarray(0,X+1);var Jc=new Int32Array(288);for(X=0;288>X;++X)fc[X]=Jc.subarray(0,X+1);var Kc=[null,pb,xb,yb,zb,Ab,Cb,Eb,nc,uc,vc,wc,xc,yc,zc,Ac];function Hc(a){var b=Array(Oa(a)+1);Ma(a,b,0,b.length);return b}
var dd={__cxa_allocate_exception:function(a){return Xb(a+16)+16},__cxa_throw:function(a,b,c){(new sb(a)).sa(b,c);tb++;throw a;},__emscripten_init_main_thread_js:function(a){Lc(a,!z,1,!qa);M.ia()},__emscripten_thread_cleanup:function(a){B?postMessage({cmd:"cleanupThread",thread:a}):hb(a)},__pthread_create_js:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return E("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var f=[],g=0,k=b?u()[b+40>>2]:0;-1==
k?k="#canvas":k&&(k=H(k).trim());k&&(k=k.split(","));var n={},p=y.canvas?y.canvas.id:"",t;for(t in k){var v=k[t].trim();try{if("#canvas"==v){if(!y.canvas){E('pthread_create: could not find canvas with ID "'+v+'" to transfer to thread!');g=28;break}v=y.canvas.id}if(N[v]){var Y=N[v];N[v]=null;y.canvas instanceof OffscreenCanvas&&v===y.canvas.id&&(y.canvas=null)}else if(!B){var G=y.canvas&&y.canvas.id===v?y.canvas:document.querySelector(v);if(!G){E('pthread_create: could not find canvas with ID "'+v+
'" to transfer to thread!');g=28;break}if(G.K){E('pthread_create: cannot transfer canvas with ID "'+v+'" to thread, since the current thread does not have control over it!');g=63;break}if(G.transferControlToOffscreen)G.g||(G.g=Xb(12),u()[G.g>>2]=G.width,u()[G.g+4>>2]=G.height,u()[G.g+8>>2]=0),Y={o:G.transferControlToOffscreen(),g:G.g,id:G.id},G.K=!0;else return E('pthread_create: cannot transfer control of canvas "'+v+'" to pthread, because current browser does not support OffscreenCanvas!'),E("pthread_create: Build with -s OFFSCREEN_FRAMEBUFFER=1 to enable fallback proxying of GL commands from pthread to main thread."),
52}Y&&(f.push(Y.o),n[Y.id]=Y)}catch(m){return E('pthread_create: failed to transfer control of canvas "'+v+'" to OffscreenCanvas! Error: '+m),28}}if(B&&(0===f.length||g))return Mc(687865856,a,b,c,d);if(g)return g;for(t in n)u()[n[t].g+8>>2]=a;a={Ga:c,U:a,C:d,u:p,O:n,La:f};return B?(a.Ma="spawnThread",postMessage(a,f),0):nb(a)},__syscall_fcntl64:xb,__syscall_fstat64:yb,__syscall_ioctl:zb,__syscall_mmap2:Ab,__syscall_munmap:Cb,__syscall_open:Eb,_emscripten_default_pthread_stack_size:function(){return 2097152},
_emscripten_futex_wait_non_blocking:function(a,b,c){var d=performance.now();c=d+c;for(Atomics.exchange(u(),Nc>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(u(),Nc>>2,0),-73;d=Atomics.exchange(u(),Nc>>2,0);if(0==d)break;mb();if(Atomics.load(u(),a>>2)!=b)return-6;Atomics.exchange(u(),Nc>>2,a)}return 0},_emscripten_notify_thread_queue:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(B)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=M.l[a])&&
a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},_emscripten_throw_longjmp:function(){throw"longjmp";},abort:function(){Ga("")},clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=rb();else return u()[Oc()>>2]=28,-1;u()[b>>2]=a/1E3|0;u()[b+4>>2]=a%1E3*1E6|0;return 0},emscripten_check_blocking_allowed:function(){A||z||(Ca||(Ca={}),Ca["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||
(Ca["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,E("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))},emscripten_get_now:rb,emscripten_glActiveTexture:function(a){U.activeTexture(a)},emscripten_glAttachShader:function(a,b){U.attachShader(P[a],Q[b])},emscripten_glBindAttribLocation:function(a,b,c){U.bindAttribLocation(P[a],
b,H(c))},emscripten_glBindBuffer:function(a,b){35051==a?U.T=b:35052==a&&(U.s=b);U.bindBuffer(a,Jb[b])},emscripten_glBindFramebuffer:function(a,b){U.bindFramebuffer(a,Kb[b])},emscripten_glBindRenderbuffer:function(a,b){U.bindRenderbuffer(a,Lb[b])},emscripten_glBindSampler:function(a,b){U.bindSampler(a,Ob[b])},emscripten_glBindTexture:function(a,b){U.bindTexture(a,Mb[b])},emscripten_glBindVertexArray:function(a){U.bindVertexArray(R[a])},emscripten_glBindVertexArrayOES:function(a){U.bindVertexArray(R[a])},
emscripten_glBlendColor:function(a,b,c,d){U.blendColor(a,b,c,d)},emscripten_glBlendEquation:function(a){U.blendEquation(a)},emscripten_glBlendFunc:function(a,b){U.blendFunc(a,b)},emscripten_glBlitFramebuffer:function(a,b,c,d,f,g,k,n,p,t){U.blitFramebuffer(a,b,c,d,f,g,k,n,p,t)},emscripten_glBufferData:function(a,b,c,d){2<=T.version?c?U.bufferData(a,r(),d,c,b):U.bufferData(a,b,d):U.bufferData(a,c?r().subarray(c,c+b):b,d)},emscripten_glBufferSubData:function(a,b,c,d){2<=T.version?U.bufferSubData(a,b,
r(),d,c):U.bufferSubData(a,b,r().subarray(d,d+c))},emscripten_glCheckFramebufferStatus:function(a){return U.checkFramebufferStatus(a)},emscripten_glClear:function(a){U.clear(a)},emscripten_glClearColor:function(a,b,c,d){U.clearColor(a,b,c,d)},emscripten_glClearStencil:function(a){U.clearStencil(a)},emscripten_glClientWaitSync:function(a,b,c,d){return U.clientWaitSync(Pb[a],b,(c>>>0)+4294967296*d)},emscripten_glColorMask:function(a,b,c,d){U.colorMask(!!a,!!b,!!c,!!d)},emscripten_glCompileShader:function(a){U.compileShader(Q[a])},
emscripten_glCompressedTexImage2D:function(a,b,c,d,f,g,k,n){2<=T.version?U.s?U.compressedTexImage2D(a,b,c,d,f,g,k,n):U.compressedTexImage2D(a,b,c,d,f,g,r(),n,k):U.compressedTexImage2D(a,b,c,d,f,g,n?r().subarray(n,n+k):null)},emscripten_glCompressedTexSubImage2D:function(a,b,c,d,f,g,k,n,p){2<=T.version?U.s?U.compressedTexSubImage2D(a,b,c,d,f,g,k,n,p):U.compressedTexSubImage2D(a,b,c,d,f,g,k,r(),p,n):U.compressedTexSubImage2D(a,b,c,d,f,g,k,p?r().subarray(p,p+n):null)},emscripten_glCopyBufferSubData:function(a,
b,c,d,f){U.copyBufferSubData(a,b,c,d,f)},emscripten_glCopyTexSubImage2D:function(a,b,c,d,f,g,k,n){U.copyTexSubImage2D(a,b,c,d,f,g,k,n)},emscripten_glCreateProgram:function(){var a=Ub(P),b=U.createProgram();b.name=a;b.N=b.L=b.M=0;b.X=1;P[a]=b;return a},emscripten_glCreateShader:function(a){var b=Ub(Q);Q[b]=U.createShader(a);return b},emscripten_glCullFace:function(a){U.cullFace(a)},emscripten_glDeleteBuffers:function(a,b){for(var c=0;c<a;c++){var d=u()[b+4*c>>2],f=Jb[d];f&&(U.deleteBuffer(f),f.name=
0,Jb[d]=null,d==U.T&&(U.T=0),d==U.s&&(U.s=0))}},emscripten_glDeleteFramebuffers:function(a,b){for(var c=0;c<a;++c){var d=u()[b+4*c>>2],f=Kb[d];f&&(U.deleteFramebuffer(f),f.name=0,Kb[d]=null)}},emscripten_glDeleteProgram:function(a){if(a){var b=P[a];b?(U.deleteProgram(b),b.name=0,P[a]=null):S(1281)}},emscripten_glDeleteRenderbuffers:function(a,b){for(var c=0;c<a;c++){var d=u()[b+4*c>>2],f=Lb[d];f&&(U.deleteRenderbuffer(f),f.name=0,Lb[d]=null)}},emscripten_glDeleteSamplers:function(a,b){for(var c=0;c<
a;c++){var d=u()[b+4*c>>2],f=Ob[d];f&&(U.deleteSampler(f),f.name=0,Ob[d]=null)}},emscripten_glDeleteShader:function(a){if(a){var b=Q[a];b?(U.deleteShader(b),Q[a]=null):S(1281)}},emscripten_glDeleteSync:function(a){if(a){var b=Pb[a];b?(U.deleteSync(b),b.name=0,Pb[a]=null):S(1281)}},emscripten_glDeleteTextures:function(a,b){for(var c=0;c<a;c++){var d=u()[b+4*c>>2],f=Mb[d];f&&(U.deleteTexture(f),f.name=0,Mb[d]=null)}},emscripten_glDeleteVertexArrays:function(a,b){for(var c=0;c<a;c++){var d=u()[b+4*c>>
2];U.deleteVertexArray(R[d]);R[d]=null}},emscripten_glDeleteVertexArraysOES:function(a,b){for(var c=0;c<a;c++){var d=u()[b+4*c>>2];U.deleteVertexArray(R[d]);R[d]=null}},emscripten_glDepthMask:function(a){U.depthMask(!!a)},emscripten_glDisable:function(a){U.disable(a)},emscripten_glDisableVertexAttribArray:function(a){U.disableVertexAttribArray(a)},emscripten_glDrawArrays:function(a,b,c){U.drawArrays(a,b,c)},emscripten_glDrawArraysInstanced:function(a,b,c,d){U.drawArraysInstanced(a,b,c,d)},emscripten_glDrawArraysInstancedBaseInstanceWEBGL:function(a,
b,c,d,f){U.Z.drawArraysInstancedBaseInstanceWEBGL(a,b,c,d,f)},emscripten_glDrawBuffers:function(a,b){for(var c=Zb[a],d=0;d<a;d++)c[d]=u()[b+4*d>>2];U.drawBuffers(c)},emscripten_glDrawElements:function(a,b,c,d){U.drawElements(a,b,c,d)},emscripten_glDrawElementsInstanced:function(a,b,c,d,f){U.drawElementsInstanced(a,b,c,d,f)},emscripten_glDrawElementsInstancedBaseVertexBaseInstanceWEBGL:function(a,b,c,d,f,g,k){U.Z.drawElementsInstancedBaseVertexBaseInstanceWEBGL(a,b,c,d,f,g,k)},emscripten_glDrawRangeElements:function(a,
b,c,d,f,g){U.drawElements(a,d,f,g)},emscripten_glEnable:function(a){U.enable(a)},emscripten_glEnableVertexAttribArray:function(a){U.enableVertexAttribArray(a)},emscripten_glFenceSync:function(a,b){return(a=U.fenceSync(a,b))?(b=Ub(Pb),a.name=b,Pb[b]=a,b):0},emscripten_glFinish:function(){U.finish()},emscripten_glFlush:function(){U.flush()},emscripten_glFramebufferRenderbuffer:function(a,b,c,d){U.framebufferRenderbuffer(a,b,c,Lb[d])},emscripten_glFramebufferTexture2D:function(a,b,c,d,f){U.framebufferTexture2D(a,
b,c,Mb[d],f)},emscripten_glFrontFace:function(a){U.frontFace(a)},emscripten_glGenBuffers:function(a,b){$b(a,b,"createBuffer",Jb)},emscripten_glGenFramebuffers:function(a,b){$b(a,b,"createFramebuffer",Kb)},emscripten_glGenRenderbuffers:function(a,b){$b(a,b,"createRenderbuffer",Lb)},emscripten_glGenSamplers:function(a,b){$b(a,b,"createSampler",Ob)},emscripten_glGenTextures:function(a,b){$b(a,b,"createTexture",Mb)},emscripten_glGenVertexArrays:function(a,b){$b(a,b,"createVertexArray",R)},emscripten_glGenVertexArraysOES:function(a,
b){$b(a,b,"createVertexArray",R)},emscripten_glGenerateMipmap:function(a){U.generateMipmap(a)},emscripten_glGetBufferParameteriv:function(a,b,c){c?u()[c>>2]=U.getBufferParameter(a,b):S(1281)},emscripten_glGetError:function(){var a=U.getError()||Tb;Tb=0;return a},emscripten_glGetFloatv:function(a,b){ac(a,b,2)},emscripten_glGetFramebufferAttachmentParameteriv:function(a,b,c,d){a=U.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u()[d>>
2]=a},emscripten_glGetIntegerv:function(a,b){ac(a,b,0)},emscripten_glGetProgramInfoLog:function(a,b,c,d){a=U.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?Na(a,d,b):0;c&&(u()[c>>2]=b)},emscripten_glGetProgramiv:function(a,b,c){if(c)if(a>=Ib)S(1281);else if(a=P[a],35716==b)a=U.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u()[c>>2]=a.length+1;else if(35719==b){if(!a.N)for(b=0;b<U.getProgramParameter(a,35718);++b)a.N=Math.max(a.N,U.getActiveUniform(a,b).name.length+1);u()[c>>
2]=a.N}else if(35722==b){if(!a.L)for(b=0;b<U.getProgramParameter(a,35721);++b)a.L=Math.max(a.L,U.getActiveAttrib(a,b).name.length+1);u()[c>>2]=a.L}else if(35381==b){if(!a.M)for(b=0;b<U.getProgramParameter(a,35382);++b)a.M=Math.max(a.M,U.getActiveUniformBlockName(a,b).length+1);u()[c>>2]=a.M}else u()[c>>2]=U.getProgramParameter(a,b);else S(1281)},emscripten_glGetRenderbufferParameteriv:function(a,b,c){c?u()[c>>2]=U.getRenderbufferParameter(a,b):S(1281)},emscripten_glGetShaderInfoLog:function(a,b,c,
d){a=U.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?Na(a,d,b):0;c&&(u()[c>>2]=b)},emscripten_glGetShaderPrecisionFormat:function(a,b,c,d){a=U.getShaderPrecisionFormat(a,b);u()[c>>2]=a.rangeMin;u()[c+4>>2]=a.rangeMax;u()[d>>2]=a.precision},emscripten_glGetShaderiv:function(a,b,c){c?35716==b?(a=U.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),a=a?a.length+1:0,u()[c>>2]=a):35720==b?(a=(a=U.getShaderSource(Q[a]))?a.length+1:0,u()[c>>2]=a):u()[c>>2]=U.getShaderParameter(Q[a],
b):S(1281)},emscripten_glGetString:function(a){var b=Qb[a];if(!b){switch(a){case 7939:b=U.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=bc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=U.getParameter(a))||S(1280);b=b&&bc(b);break;case 7938:b=U.getParameter(7938);b=2<=T.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=bc(b);break;case 35724:b=U.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&
(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=bc(b);break;default:S(1280)}Qb[a]=b}return b},emscripten_glGetStringi:function(a,b){if(2>T.version)return S(1282),0;var c=Rb[a];if(c)return 0>b||b>=c.length?(S(1281),0):c[b];switch(a){case 7939:return c=U.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return bc(d)}),c=Rb[a]=c,0>b||b>=c.length?(S(1281),0):c[b];default:return S(1280),0}},emscripten_glGetUniformLocation:function(a,b){b=H(b);if(a=P[a]){var c=
a,d=c.I,f=c.ka,g;if(!d)for(c.I=d={},c.ja={},g=0;g<U.getProgramParameter(c,35718);++g){var k=U.getActiveUniform(c,g);var n=k.name;k=k.size;var p=cc(n);p=0<p?n.slice(0,p):n;var t=c.X;c.X+=k;f[p]=[k,t];for(n=0;n<k;++n)d[t]=n,c.ja[t++]=p}c=a.I;d=0;f=b;g=cc(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,f=b.slice(0,g));if((f=a.ka[f])&&d<f[0]&&(d+=f[1],c[d]=c[d]||U.getUniformLocation(a,b)))return d}else S(1281);return-1},emscripten_glInvalidateFramebuffer:function(a,b,c){for(var d=Zb[b],f=0;f<b;f++)d[f]=u()[c+4*
f>>2];U.invalidateFramebuffer(a,d)},emscripten_glInvalidateSubFramebuffer:function(a,b,c,d,f,g,k){for(var n=Zb[b],p=0;p<b;p++)n[p]=u()[c+4*p>>2];U.invalidateSubFramebuffer(a,n,d,f,g,k)},emscripten_glIsSync:function(a){return U.isSync(Pb[a])},emscripten_glIsTexture:function(a){return(a=Mb[a])?U.isTexture(a):0},emscripten_glLineWidth:function(a){U.lineWidth(a)},emscripten_glLinkProgram:function(a){a=P[a];U.linkProgram(a);a.I=0;a.ka={}},emscripten_glMultiDrawArraysInstancedBaseInstanceWEBGL:function(a,
b,c,d,f,g){U.fa.multiDrawArraysInstancedBaseInstanceWEBGL(a,u(),b>>2,u(),c>>2,u(),d>>2,da(),f>>2,g)},emscripten_glMultiDrawElementsInstancedBaseVertexBaseInstanceWEBGL:function(a,b,c,d,f,g,k,n){U.fa.multiDrawElementsInstancedBaseVertexBaseInstanceWEBGL(a,u(),b>>2,c,u(),d>>2,u(),f>>2,u(),g>>2,da(),k>>2,n)},emscripten_glPixelStorei:function(a,b){3317==a&&(Sb=b);U.pixelStorei(a,b)},emscripten_glReadBuffer:function(a){U.readBuffer(a)},emscripten_glReadPixels:function(a,b,c,d,f,g,k){if(2<=T.version)if(U.T)U.readPixels(a,
b,c,d,f,g,k);else{var n=dc(g);U.readPixels(a,b,c,d,f,g,n,k>>31-Math.clz32(n.BYTES_PER_ELEMENT))}else(k=ec(g,f,c,d,k))?U.readPixels(a,b,c,d,f,g,k):S(1280)},emscripten_glRenderbufferStorage:function(a,b,c,d){U.renderbufferStorage(a,b,c,d)},emscripten_glRenderbufferStorageMultisample:function(a,b,c,d,f){U.renderbufferStorageMultisample(a,b,c,d,f)},emscripten_glSamplerParameterf:function(a,b,c){U.samplerParameterf(Ob[a],b,c)},emscripten_glSamplerParameteri:function(a,b,c){U.samplerParameteri(Ob[a],b,
c)},emscripten_glSamplerParameteriv:function(a,b,c){c=u()[c>>2];U.samplerParameteri(Ob[a],b,c)},emscripten_glScissor:function(a,b,c,d){U.scissor(a,b,c,d)},emscripten_glShaderSource:function(a,b,c,d){for(var f="",g=0;g<b;++g){var k=d?u()[d+4*g>>2]:-1;f+=H(u()[c+4*g>>2],0>k?void 0:k)}U.shaderSource(Q[a],f)},emscripten_glStencilFunc:function(a,b,c){U.stencilFunc(a,b,c)},emscripten_glStencilFuncSeparate:function(a,b,c,d){U.stencilFuncSeparate(a,b,c,d)},emscripten_glStencilMask:function(a){U.stencilMask(a)},
emscripten_glStencilMaskSeparate:function(a,b){U.stencilMaskSeparate(a,b)},emscripten_glStencilOp:function(a,b,c){U.stencilOp(a,b,c)},emscripten_glStencilOpSeparate:function(a,b,c,d){U.stencilOpSeparate(a,b,c,d)},emscripten_glTexImage2D:function(a,b,c,d,f,g,k,n,p){if(2<=T.version)if(U.s)U.texImage2D(a,b,c,d,f,g,k,n,p);else if(p){var t=dc(n);U.texImage2D(a,b,c,d,f,g,k,n,t,p>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else U.texImage2D(a,b,c,d,f,g,k,n,null);else U.texImage2D(a,b,c,d,f,g,k,n,p?ec(n,k,d,f,p):
null)},emscripten_glTexParameterf:function(a,b,c){U.texParameterf(a,b,c)},emscripten_glTexParameterfv:function(a,b,c){c=w()[c>>2];U.texParameterf(a,b,c)},emscripten_glTexParameteri:function(a,b,c){U.texParameteri(a,b,c)},emscripten_glTexParameteriv:function(a,b,c){c=u()[c>>2];U.texParameteri(a,b,c)},emscripten_glTexStorage2D:function(a,b,c,d,f){U.texStorage2D(a,b,c,d,f)},emscripten_glTexSubImage2D:function(a,b,c,d,f,g,k,n,p){if(2<=T.version)if(U.s)U.texSubImage2D(a,b,c,d,f,g,k,n,p);else if(p){var t=
dc(n);U.texSubImage2D(a,b,c,d,f,g,k,n,t,p>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else U.texSubImage2D(a,b,c,d,f,g,k,n,null);else t=null,p&&(t=ec(n,k,f,g,p)),U.texSubImage2D(a,b,c,d,f,g,k,n,t)},emscripten_glUniform1f:function(a,b){U.uniform1f(V(a),b)},emscripten_glUniform1fv:function(a,b,c){if(2<=T.version)U.uniform1fv(V(a),w(),c>>2,b);else{if(288>=b)for(var d=W[b-1],f=0;f<b;++f)d[f]=w()[c+4*f>>2];else d=w().subarray(c>>2,c+4*b>>2);U.uniform1fv(V(a),d)}},emscripten_glUniform1i:function(a,b){U.uniform1i(V(a),
b)},emscripten_glUniform1iv:function(a,b,c){if(2<=T.version)U.uniform1iv(V(a),u(),c>>2,b);else{if(288>=b)for(var d=fc[b-1],f=0;f<b;++f)d[f]=u()[c+4*f>>2];else d=u().subarray(c>>2,c+4*b>>2);U.uniform1iv(V(a),d)}},emscripten_glUniform2f:function(a,b,c){U.uniform2f(V(a),b,c)},emscripten_glUniform2fv:function(a,b,c){if(2<=T.version)U.uniform2fv(V(a),w(),c>>2,2*b);else{if(144>=b)for(var d=W[2*b-1],f=0;f<2*b;f+=2)d[f]=w()[c+4*f>>2],d[f+1]=w()[c+(4*f+4)>>2];else d=w().subarray(c>>2,c+8*b>>2);U.uniform2fv(V(a),
d)}},emscripten_glUniform2i:function(a,b,c){U.uniform2i(V(a),b,c)},emscripten_glUniform2iv:function(a,b,c){if(2<=T.version)U.uniform2iv(V(a),u(),c>>2,2*b);else{if(144>=b)for(var d=fc[2*b-1],f=0;f<2*b;f+=2)d[f]=u()[c+4*f>>2],d[f+1]=u()[c+(4*f+4)>>2];else d=u().subarray(c>>2,c+8*b>>2);U.uniform2iv(V(a),d)}},emscripten_glUniform3f:function(a,b,c,d){U.uniform3f(V(a),b,c,d)},emscripten_glUniform3fv:function(a,b,c){if(2<=T.version)U.uniform3fv(V(a),w(),c>>2,3*b);else{if(96>=b)for(var d=W[3*b-1],f=0;f<3*
b;f+=3)d[f]=w()[c+4*f>>2],d[f+1]=w()[c+(4*f+4)>>2],d[f+2]=w()[c+(4*f+8)>>2];else d=w().subarray(c>>2,c+12*b>>2);U.uniform3fv(V(a),d)}},emscripten_glUniform3i:function(a,b,c,d){U.uniform3i(V(a),b,c,d)},emscripten_glUniform3iv:function(a,b,c){if(2<=T.version)U.uniform3iv(V(a),u(),c>>2,3*b);else{if(96>=b)for(var d=fc[3*b-1],f=0;f<3*b;f+=3)d[f]=u()[c+4*f>>2],d[f+1]=u()[c+(4*f+4)>>2],d[f+2]=u()[c+(4*f+8)>>2];else d=u().subarray(c>>2,c+12*b>>2);U.uniform3iv(V(a),d)}},emscripten_glUniform4f:function(a,b,
c,d,f){U.uniform4f(V(a),b,c,d,f)},emscripten_glUniform4fv:function(a,b,c){if(2<=T.version)U.uniform4fv(V(a),w(),c>>2,4*b);else{if(72>=b){var d=W[4*b-1],f=w();c>>=2;for(var g=0;g<4*b;g+=4){var k=c+g;d[g]=f[k];d[g+1]=f[k+1];d[g+2]=f[k+2];d[g+3]=f[k+3]}}else d=w().subarray(c>>2,c+16*b>>2);U.uniform4fv(V(a),d)}},emscripten_glUniform4i:function(a,b,c,d,f){U.uniform4i(V(a),b,c,d,f)},emscripten_glUniform4iv:function(a,b,c){if(2<=T.version)U.uniform4iv(V(a),u(),c>>2,4*b);else{if(72>=b)for(var d=fc[4*b-1],
f=0;f<4*b;f+=4)d[f]=u()[c+4*f>>2],d[f+1]=u()[c+(4*f+4)>>2],d[f+2]=u()[c+(4*f+8)>>2],d[f+3]=u()[c+(4*f+12)>>2];else d=u().subarray(c>>2,c+16*b>>2);U.uniform4iv(V(a),d)}},emscripten_glUniformMatrix2fv:function(a,b,c,d){if(2<=T.version)U.uniformMatrix2fv(V(a),!!c,w(),d>>2,4*b);else{if(72>=b)for(var f=W[4*b-1],g=0;g<4*b;g+=4)f[g]=w()[d+4*g>>2],f[g+1]=w()[d+(4*g+4)>>2],f[g+2]=w()[d+(4*g+8)>>2],f[g+3]=w()[d+(4*g+12)>>2];else f=w().subarray(d>>2,d+16*b>>2);U.uniformMatrix2fv(V(a),!!c,f)}},emscripten_glUniformMatrix3fv:function(a,
b,c,d){if(2<=T.version)U.uniformMatrix3fv(V(a),!!c,w(),d>>2,9*b);else{if(32>=b)for(var f=W[9*b-1],g=0;g<9*b;g+=9)f[g]=w()[d+4*g>>2],f[g+1]=w()[d+(4*g+4)>>2],f[g+2]=w()[d+(4*g+8)>>2],f[g+3]=w()[d+(4*g+12)>>2],f[g+4]=w()[d+(4*g+16)>>2],f[g+5]=w()[d+(4*g+20)>>2],f[g+6]=w()[d+(4*g+24)>>2],f[g+7]=w()[d+(4*g+28)>>2],f[g+8]=w()[d+(4*g+32)>>2];else f=w().subarray(d>>2,d+36*b>>2);U.uniformMatrix3fv(V(a),!!c,f)}},emscripten_glUniformMatrix4fv:function(a,b,c,d){if(2<=T.version)U.uniformMatrix4fv(V(a),!!c,w(),
d>>2,16*b);else{if(18>=b){var f=W[16*b-1],g=w();d>>=2;for(var k=0;k<16*b;k+=16){var n=d+k;f[k]=g[n];f[k+1]=g[n+1];f[k+2]=g[n+2];f[k+3]=g[n+3];f[k+4]=g[n+4];f[k+5]=g[n+5];f[k+6]=g[n+6];f[k+7]=g[n+7];f[k+8]=g[n+8];f[k+9]=g[n+9];f[k+10]=g[n+10];f[k+11]=g[n+11];f[k+12]=g[n+12];f[k+13]=g[n+13];f[k+14]=g[n+14];f[k+15]=g[n+15]}}else f=w().subarray(d>>2,d+64*b>>2);U.uniformMatrix4fv(V(a),!!c,f)}},emscripten_glUseProgram:function(a){a=P[a];U.useProgram(a);U.ma=a},emscripten_glVertexAttrib1f:function(a,b){U.vertexAttrib1f(a,
b)},emscripten_glVertexAttrib2fv:function(a,b){U.vertexAttrib2f(a,w()[b>>2],w()[b+4>>2])},emscripten_glVertexAttrib3fv:function(a,b){U.vertexAttrib3f(a,w()[b>>2],w()[b+4>>2],w()[b+8>>2])},emscripten_glVertexAttrib4fv:function(a,b){U.vertexAttrib4f(a,w()[b>>2],w()[b+4>>2],w()[b+8>>2],w()[b+12>>2])},emscripten_glVertexAttribDivisor:function(a,b){U.vertexAttribDivisor(a,b)},emscripten_glVertexAttribIPointer:function(a,b,c,d,f){U.vertexAttribIPointer(a,b,c,d,f)},emscripten_glVertexAttribPointer:function(a,
b,c,d,f,g){U.vertexAttribPointer(a,b,c,!!d,f,g)},emscripten_glViewport:function(a,b,c,d){U.viewport(a,b,c,d)},emscripten_glWaitSync:function(a,b,c,d){U.waitSync(Pb[a],b,(c>>>0)+4294967296*d)},emscripten_receive_on_main_thread_js:function(a,b,c){ic.length=b;c>>=3;for(var d=0;d<b;d++)ic[d]=ia()[c+d];return(0>a?eb[-a-1]:Kc[a]).apply(null,ic)},emscripten_resize_heap:function(a){var b=r().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,
d);0<d%65536&&(d+=65536-d%65536);a:{try{h.grow(Math.min(2147483648,d)-l.byteLength+65535>>>16);q(h.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},emscripten_set_canvas_element_size:function(a,b,c){return lc(a)?mc(a,b,c):nc(a,b,c)},emscripten_unwind_to_js_event_loop:function(){throw"unwind";},emscripten_webgl_create_context:function(a,b){return pc(a,b)},emscripten_webgl_init_context_attributes:function(a){for(var b=a>>2,c=0;14>c;++c)u()[b+c]=0;u()[b]=u()[b+1]=u()[b+3]=u()[b+4]=
u()[b+8]=u()[b+10]=1;z&&(u()[a+48>>2]=1)},emscripten_webgl_make_context_current:function(a){T=Nb[a];y.Na=U=T&&T.B;return!a||U?0:-5},environ_get:uc,environ_sizes_get:vc,exit:function(a){qb(a)},fd_close:wc,fd_pread:xc,fd_read:yc,fd_seek:zc,fd_write:Ac,getTempRet0:function(){return Ea},invoke_ii:Pc,invoke_iii:Qc,invoke_iiii:Rc,invoke_iiiii:Sc,invoke_iiiiii:Tc,invoke_iiiiiii:Uc,invoke_v:Vc,invoke_vi:Wc,invoke_vii:Xc,invoke_viii:Yc,invoke_viiii:Zc,invoke_viiiii:$c,invoke_viiiiii:ad,invoke_viiiiiii:bd,
invoke_viiiiiiii:cd,memory:h||y.wasmMemory,setTempRet0:function(a){Ea=a},strftime_l:function(a,b,c,d){return Gc(a,b,c,d)}};
(function(){function a(f,g){y.asm=f.exports;M.W.push(y.asm.emscripten_tls_init);Ta=y.asm.__indirect_function_table;Va.unshift(y.asm.__wasm_call_ctors);Ha=g;if(!B){var k=M.m.length;M.m.forEach(function(n){M.da(n,function(){if(!--k&&(Za--,y.monitorRunDependencies&&y.monitorRunDependencies(Za),0==Za&&(null!==$a&&(clearInterval($a),$a=null),ab))){var p=ab;ab=null;p()}})})}}function b(f){a(f.instance,f.module)}function c(f){return db().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(f,
function(g){E("failed to asynchronously prepare wasm: "+g);Ga(g)})}var d={env:dd,wasi_snapshot_preview1:dd};B||(Za++,y.monitorRunDependencies&&y.monitorRunDependencies(Za));if(y.instantiateWasm)try{return y.instantiateWasm(d,a)}catch(f){return E("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return Fa||"function"!==typeof WebAssembly.instantiateStreaming||bb()||I.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(I,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,
d).then(b,function(g){E("wasm streaming compile failed: "+g);E("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ma);return{}})();y.___wasm_call_ctors=function(){return(y.___wasm_call_ctors=y.asm.__wasm_call_ctors).apply(null,arguments)};y._canvas_destroy=function(){return(y._canvas_destroy=y.asm.canvas_destroy).apply(null,arguments)};y._canvas_saveLayer=function(){return(y._canvas_saveLayer=y.asm.canvas_saveLayer).apply(null,arguments)};
y._canvas_save=function(){return(y._canvas_save=y.asm.canvas_save).apply(null,arguments)};y._canvas_restore=function(){return(y._canvas_restore=y.asm.canvas_restore).apply(null,arguments)};y._canvas_restoreToCount=function(){return(y._canvas_restoreToCount=y.asm.canvas_restoreToCount).apply(null,arguments)};y._canvas_getSaveCount=function(){return(y._canvas_getSaveCount=y.asm.canvas_getSaveCount).apply(null,arguments)};
y._canvas_translate=function(){return(y._canvas_translate=y.asm.canvas_translate).apply(null,arguments)};y._canvas_scale=function(){return(y._canvas_scale=y.asm.canvas_scale).apply(null,arguments)};y._canvas_rotate=function(){return(y._canvas_rotate=y.asm.canvas_rotate).apply(null,arguments)};y._canvas_skew=function(){return(y._canvas_skew=y.asm.canvas_skew).apply(null,arguments)};y._canvas_transform=function(){return(y._canvas_transform=y.asm.canvas_transform).apply(null,arguments)};
y._canvas_clipRect=function(){return(y._canvas_clipRect=y.asm.canvas_clipRect).apply(null,arguments)};y._canvas_clipRRect=function(){return(y._canvas_clipRRect=y.asm.canvas_clipRRect).apply(null,arguments)};y._canvas_clipPath=function(){return(y._canvas_clipPath=y.asm.canvas_clipPath).apply(null,arguments)};y._canvas_drawColor=function(){return(y._canvas_drawColor=y.asm.canvas_drawColor).apply(null,arguments)};
y._canvas_drawLine=function(){return(y._canvas_drawLine=y.asm.canvas_drawLine).apply(null,arguments)};y._canvas_drawPaint=function(){return(y._canvas_drawPaint=y.asm.canvas_drawPaint).apply(null,arguments)};y._canvas_drawRect=function(){return(y._canvas_drawRect=y.asm.canvas_drawRect).apply(null,arguments)};y._canvas_drawRRect=function(){return(y._canvas_drawRRect=y.asm.canvas_drawRRect).apply(null,arguments)};
y._canvas_drawDRRect=function(){return(y._canvas_drawDRRect=y.asm.canvas_drawDRRect).apply(null,arguments)};y._canvas_drawOval=function(){return(y._canvas_drawOval=y.asm.canvas_drawOval).apply(null,arguments)};y._canvas_drawCircle=function(){return(y._canvas_drawCircle=y.asm.canvas_drawCircle).apply(null,arguments)};y._canvas_drawArc=function(){return(y._canvas_drawArc=y.asm.canvas_drawArc).apply(null,arguments)};
y._canvas_drawPath=function(){return(y._canvas_drawPath=y.asm.canvas_drawPath).apply(null,arguments)};y._canvas_drawShadow=function(){return(y._canvas_drawShadow=y.asm.canvas_drawShadow).apply(null,arguments)};y._canvas_drawPicture=function(){return(y._canvas_drawPicture=y.asm.canvas_drawPicture).apply(null,arguments)};y._canvas_getTransform=function(){return(y._canvas_getTransform=y.asm.canvas_getTransform).apply(null,arguments)};
y._canvas_getLocalClipBounds=function(){return(y._canvas_getLocalClipBounds=y.asm.canvas_getLocalClipBounds).apply(null,arguments)};y._canvas_getDeviceClipBounds=function(){return(y._canvas_getDeviceClipBounds=y.asm.canvas_getDeviceClipBounds).apply(null,arguments)};y._contourMeasureIter_create=function(){return(y._contourMeasureIter_create=y.asm.contourMeasureIter_create).apply(null,arguments)};
y._contourMeasureIter_next=function(){return(y._contourMeasureIter_next=y.asm.contourMeasureIter_next).apply(null,arguments)};y._contourMeasure_dispose=function(){return(y._contourMeasure_dispose=y.asm.contourMeasure_dispose).apply(null,arguments)};y._contourMeasure_length=function(){return(y._contourMeasure_length=y.asm.contourMeasure_length).apply(null,arguments)};y._contourMeasure_isClosed=function(){return(y._contourMeasure_isClosed=y.asm.contourMeasure_isClosed).apply(null,arguments)};
y._contourMeasure_getPosTan=function(){return(y._contourMeasure_getPosTan=y.asm.contourMeasure_getPosTan).apply(null,arguments)};y._contourMeasure_getSegment=function(){return(y._contourMeasure_getSegment=y.asm.contourMeasure_getSegment).apply(null,arguments)};y._paint_create=function(){return(y._paint_create=y.asm.paint_create).apply(null,arguments)};y._paint_destroy=function(){return(y._paint_destroy=y.asm.paint_destroy).apply(null,arguments)};
y._paint_setBlendMode=function(){return(y._paint_setBlendMode=y.asm.paint_setBlendMode).apply(null,arguments)};y._paint_setStyle=function(){return(y._paint_setStyle=y.asm.paint_setStyle).apply(null,arguments)};y._paint_getStyle=function(){return(y._paint_getStyle=y.asm.paint_getStyle).apply(null,arguments)};y._paint_setStrokeWidth=function(){return(y._paint_setStrokeWidth=y.asm.paint_setStrokeWidth).apply(null,arguments)};
y._paint_getStrokeWidth=function(){return(y._paint_getStrokeWidth=y.asm.paint_getStrokeWidth).apply(null,arguments)};y._paint_setStrokeCap=function(){return(y._paint_setStrokeCap=y.asm.paint_setStrokeCap).apply(null,arguments)};y._paint_getStrokeCap=function(){return(y._paint_getStrokeCap=y.asm.paint_getStrokeCap).apply(null,arguments)};y._paint_setStrokeJoin=function(){return(y._paint_setStrokeJoin=y.asm.paint_setStrokeJoin).apply(null,arguments)};
y._paint_getStrokeJoin=function(){return(y._paint_getStrokeJoin=y.asm.paint_getStrokeJoin).apply(null,arguments)};y._paint_setAntiAlias=function(){return(y._paint_setAntiAlias=y.asm.paint_setAntiAlias).apply(null,arguments)};y._paint_getAntiAlias=function(){return(y._paint_getAntiAlias=y.asm.paint_getAntiAlias).apply(null,arguments)};y._paint_setColorInt=function(){return(y._paint_setColorInt=y.asm.paint_setColorInt).apply(null,arguments)};
y._paint_getColorInt=function(){return(y._paint_getColorInt=y.asm.paint_getColorInt).apply(null,arguments)};y._paint_setMiterLimit=function(){return(y._paint_setMiterLimit=y.asm.paint_setMiterLimit).apply(null,arguments)};y._paint_getMiterLImit=function(){return(y._paint_getMiterLImit=y.asm.paint_getMiterLImit).apply(null,arguments)};y._path_create=function(){return(y._path_create=y.asm.path_create).apply(null,arguments)};
y._path_destroy=function(){return(y._path_destroy=y.asm.path_destroy).apply(null,arguments)};y._path_copy=function(){return(y._path_copy=y.asm.path_copy).apply(null,arguments)};y._path_setFillType=function(){return(y._path_setFillType=y.asm.path_setFillType).apply(null,arguments)};y._path_getFillType=function(){return(y._path_getFillType=y.asm.path_getFillType).apply(null,arguments)};y._path_moveTo=function(){return(y._path_moveTo=y.asm.path_moveTo).apply(null,arguments)};
y._path_relativeMoveTo=function(){return(y._path_relativeMoveTo=y.asm.path_relativeMoveTo).apply(null,arguments)};y._path_lineTo=function(){return(y._path_lineTo=y.asm.path_lineTo).apply(null,arguments)};y._path_relativeLineTo=function(){return(y._path_relativeLineTo=y.asm.path_relativeLineTo).apply(null,arguments)};y._path_quadraticBezierTo=function(){return(y._path_quadraticBezierTo=y.asm.path_quadraticBezierTo).apply(null,arguments)};
y._path_relativeQuadraticBezierTo=function(){return(y._path_relativeQuadraticBezierTo=y.asm.path_relativeQuadraticBezierTo).apply(null,arguments)};y._path_cubicTo=function(){return(y._path_cubicTo=y.asm.path_cubicTo).apply(null,arguments)};y._path_relativeCubicTo=function(){return(y._path_relativeCubicTo=y.asm.path_relativeCubicTo).apply(null,arguments)};y._path_conicTo=function(){return(y._path_conicTo=y.asm.path_conicTo).apply(null,arguments)};
y._path_relativeConicTo=function(){return(y._path_relativeConicTo=y.asm.path_relativeConicTo).apply(null,arguments)};y._path_arcToOval=function(){return(y._path_arcToOval=y.asm.path_arcToOval).apply(null,arguments)};y._path_arcToRotated=function(){return(y._path_arcToRotated=y.asm.path_arcToRotated).apply(null,arguments)};y._path_relativeArcToRotated=function(){return(y._path_relativeArcToRotated=y.asm.path_relativeArcToRotated).apply(null,arguments)};
y._path_addRect=function(){return(y._path_addRect=y.asm.path_addRect).apply(null,arguments)};y._path_addOval=function(){return(y._path_addOval=y.asm.path_addOval).apply(null,arguments)};y._path_addArc=function(){return(y._path_addArc=y.asm.path_addArc).apply(null,arguments)};y._path_addPolygon=function(){return(y._path_addPolygon=y.asm.path_addPolygon).apply(null,arguments)};y._path_addRRect=function(){return(y._path_addRRect=y.asm.path_addRRect).apply(null,arguments)};
y._path_addPath=function(){return(y._path_addPath=y.asm.path_addPath).apply(null,arguments)};y._path_close=function(){return(y._path_close=y.asm.path_close).apply(null,arguments)};y._path_reset=function(){return(y._path_reset=y.asm.path_reset).apply(null,arguments)};y._path_contains=function(){return(y._path_contains=y.asm.path_contains).apply(null,arguments)};y._path_transform=function(){return(y._path_transform=y.asm.path_transform).apply(null,arguments)};
y._path_getBounds=function(){return(y._path_getBounds=y.asm.path_getBounds).apply(null,arguments)};y._path_combine=function(){return(y._path_combine=y.asm.path_combine).apply(null,arguments)};y._pictureRecorder_create=function(){return(y._pictureRecorder_create=y.asm.pictureRecorder_create).apply(null,arguments)};y._pictureRecorder_dispose=function(){return(y._pictureRecorder_dispose=y.asm.pictureRecorder_dispose).apply(null,arguments)};
y._pictureRecorder_beginRecording=function(){return(y._pictureRecorder_beginRecording=y.asm.pictureRecorder_beginRecording).apply(null,arguments)};y._pictureRecorder_endRecording=function(){return(y._pictureRecorder_endRecording=y.asm.pictureRecorder_endRecording).apply(null,arguments)};y._picture_getCullRect=function(){return(y._picture_getCullRect=y.asm.picture_getCullRect).apply(null,arguments)};y._picture_dispose=function(){return(y._picture_dispose=y.asm.picture_dispose).apply(null,arguments)};
y._picture_approximateBytesUsed=function(){return(y._picture_approximateBytesUsed=y.asm.picture_approximateBytesUsed).apply(null,arguments)};y._surface_createFromCanvas=function(){return(y._surface_createFromCanvas=y.asm.surface_createFromCanvas).apply(null,arguments)};y._surface_setOnRenderCallback=function(){return(y._surface_setOnRenderCallback=y.asm.surface_setOnRenderCallback).apply(null,arguments)};y._surface_destroy=function(){return(y._surface_destroy=y.asm.surface_destroy).apply(null,arguments)};
y._surface_setCanvasSize=function(){return(y._surface_setCanvasSize=y.asm.surface_setCanvasSize).apply(null,arguments)};y._surface_renderPicture=function(){return(y._surface_renderPicture=y.asm.surface_renderPicture).apply(null,arguments)};
var kc=y._emscripten_dispatch_to_thread_=function(){return(kc=y._emscripten_dispatch_to_thread_=y.asm.emscripten_dispatch_to_thread_).apply(null,arguments)},Oc=y.___errno_location=function(){return(Oc=y.___errno_location=y.asm.__errno_location).apply(null,arguments)},lb=y._pthread_self=function(){return(lb=y._pthread_self=y.asm.pthread_self).apply(null,arguments)},Db=y._free=function(){return(Db=y._free=y.asm.free).apply(null,arguments)},Xb=y._malloc=function(){return(Xb=y._malloc=y.asm.malloc).apply(null,
arguments)};y._emscripten_tls_init=function(){return(y._emscripten_tls_init=y.asm.emscripten_tls_init).apply(null,arguments)};var mb=y._emscripten_main_thread_process_queued_calls=function(){return(mb=y._emscripten_main_thread_process_queued_calls=y.asm.emscripten_main_thread_process_queued_calls).apply(null,arguments)},Lc=y.__emscripten_thread_init=function(){return(Lc=y.__emscripten_thread_init=y.asm._emscripten_thread_init).apply(null,arguments)};
y._emscripten_current_thread_process_queued_calls=function(){return(y._emscripten_current_thread_process_queued_calls=y.asm.emscripten_current_thread_process_queued_calls).apply(null,arguments)};
var Mc=y._emscripten_sync_run_in_main_thread_4=function(){return(Mc=y._emscripten_sync_run_in_main_thread_4=y.asm.emscripten_sync_run_in_main_thread_4).apply(null,arguments)},hc=y._emscripten_run_in_main_runtime_thread_js=function(){return(hc=y._emscripten_run_in_main_runtime_thread_js=y.asm.emscripten_run_in_main_runtime_thread_js).apply(null,arguments)},ib=y.__emscripten_thread_free_data=function(){return(ib=y.__emscripten_thread_free_data=y.asm._emscripten_thread_free_data).apply(null,arguments)};
y.__emscripten_thread_exit=function(){return(y.__emscripten_thread_exit=y.asm._emscripten_thread_exit).apply(null,arguments)};
var Bb=y._memalign=function(){return(Bb=y._memalign=y.asm.memalign).apply(null,arguments)},Z=y._setThrew=function(){return(Z=y._setThrew=y.asm.setThrew).apply(null,arguments)},ob=y._emscripten_stack_set_limits=function(){return(ob=y._emscripten_stack_set_limits=y.asm.emscripten_stack_set_limits).apply(null,arguments)},K=y.stackSave=function(){return(K=y.stackSave=y.asm.stackSave).apply(null,arguments)},L=y.stackRestore=function(){return(L=y.stackRestore=y.asm.stackRestore).apply(null,arguments)},
gc=y.stackAlloc=function(){return(gc=y.stackAlloc=y.asm.stackAlloc).apply(null,arguments)},Nc=y.__emscripten_main_thread_futex=246984,jb=y.__emscripten_allow_main_runtime_queued_calls=243908;function Xc(a,b,c){var d=K();try{J(a)(b,c)}catch(f){L(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function Qc(a,b,c){var d=K();try{return J(a)(b,c)}catch(f){L(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}
function cd(a,b,c,d,f,g,k,n,p){var t=K();try{J(a)(b,c,d,f,g,k,n,p)}catch(v){L(t);if(v!==v+0&&"longjmp"!==v)throw v;Z(1,0)}}function Vc(a){var b=K();try{J(a)()}catch(c){L(b);if(c!==c+0&&"longjmp"!==c)throw c;Z(1,0)}}function Pc(a,b){var c=K();try{return J(a)(b)}catch(d){L(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function Wc(a,b){var c=K();try{J(a)(b)}catch(d){L(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}
function Sc(a,b,c,d,f){var g=K();try{return J(a)(b,c,d,f)}catch(k){L(g);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}function Rc(a,b,c,d){var f=K();try{return J(a)(b,c,d)}catch(g){L(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}function Yc(a,b,c,d){var f=K();try{J(a)(b,c,d)}catch(g){L(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}function $c(a,b,c,d,f,g){var k=K();try{J(a)(b,c,d,f,g)}catch(n){L(k);if(n!==n+0&&"longjmp"!==n)throw n;Z(1,0)}}
function Uc(a,b,c,d,f,g,k){var n=K();try{return J(a)(b,c,d,f,g,k)}catch(p){L(n);if(p!==p+0&&"longjmp"!==p)throw p;Z(1,0)}}function Tc(a,b,c,d,f,g){var k=K();try{return J(a)(b,c,d,f,g)}catch(n){L(k);if(n!==n+0&&"longjmp"!==n)throw n;Z(1,0)}}function Zc(a,b,c,d,f){var g=K();try{J(a)(b,c,d,f)}catch(k){L(g);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}function ad(a,b,c,d,f,g,k){var n=K();try{J(a)(b,c,d,f,g,k)}catch(p){L(n);if(p!==p+0&&"longjmp"!==p)throw p;Z(1,0)}}
function bd(a,b,c,d,f,g,k,n){var p=K();try{J(a)(b,c,d,f,g,k,n)}catch(t){L(p);if(t!==t+0&&"longjmp"!==t)throw t;Z(1,0)}}
y.addFunction=function(a,b){if(!F){F=new WeakMap;for(var c=Ta.length,d=0;d<0+c;d++){var f=J(d);f&&F.set(f,d)}}if(F.has(a))return F.get(a);if(Da.length)c=Da.pop();else{try{Ta.grow(1)}catch(n){if(!(n instanceof RangeError))throw n;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}c=Ta.length-1}try{Ta.set(c,a)}catch(n){if(!(n instanceof TypeError))throw n;if("function"===typeof WebAssembly.Function){f={i:"i32",j:"i64",f:"f32",d:"f64"};var g={parameters:[],results:"v"==b[0]?[]:[f[b[0]]]};for(d=
1;d<b.length;++d)g.parameters.push(f[b[d]]);b=new WebAssembly.Function(g,a)}else{f=[1,0,1,96];g=b.slice(0,1);b=b.slice(1);var k={i:127,j:126,f:125,d:124};f.push(b.length);for(d=0;d<b.length;++d)f.push(k[b[d]]);"v"==g?f.push(0):f=f.concat([1,k[g]]);f[1]=f.length-2;b=new Uint8Array([0,97,115,109,1,0,0,0].concat(f,[2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0]));b=new WebAssembly.Module(b);b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f}Ta.set(c,b)}F.set(a,c);return c};
y.removeFunction=function(a){F.delete(J(a));Da.push(a)};y.keepRuntimeAlive=ya;y.PThread=M;y.PThread=M;y.wasmMemory=h;y.ExitStatus=xa;var ed;function xa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ab=function fd(){ed||gd();ed||(ab=fd)};
function gd(){function a(){if(!ed&&(ed=!0,y.calledRun=!0,!Ia)){B||fb(Va);la(y);if(y.onRuntimeInitialized)y.onRuntimeInitialized();if(!B){if(y.postRun)for("function"==typeof y.postRun&&(y.postRun=[y.postRun]);y.postRun.length;){var b=y.postRun.shift();Wa.unshift(b)}fb(Wa)}}}if(!(0<Za))if(B)la(y),B||fb(Va),postMessage({cmd:"loaded"});else{if(y.preRun)for("function"==typeof y.preRun&&(y.preRun=[y.preRun]);y.preRun.length;)Ya();fb(Ua);0<Za||(y.setStatus?(y.setStatus("Running..."),setTimeout(function(){setTimeout(function(){y.setStatus("")},
1);a()},1)):a())}}y.run=gd;function qb(a){if(B)throw pb(a),"unwind";ya()||B||M.ha();if(!ya()){M.ha();if(y.onExit)y.onExit(a);Ia=!0}pa(a,new xa(a))}if(y.preInit)for("function"==typeof y.preInit&&(y.preInit=[y.preInit]);0<y.preInit.length;)y.preInit.pop()();B&&(noExitRuntime=!1,M.va());gd();


  return skwasm.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = skwasm;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return skwasm; });
else if (typeof exports === 'object')
  exports["skwasm"] = skwasm;
