
var skwasm = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(skwasm = {})  {

function c(){h.buffer!=m.buffer&&q();return m}function r(){h.buffer!=m.buffer&&q();return aa}function u(){h.buffer!=m.buffer&&q();return ba}function w(){h.buffer!=m.buffer&&q();return ca}function y(){h.buffer!=m.buffer&&q();return da}function fa(){h.buffer!=m.buffer&&q();return ha}var z;z||(z=typeof skwasm !== 'undefined' ? skwasm : {});var ia,ja;z.ready=new Promise(function(a,b){ia=a;ja=b});
var ka=Object.assign({},z),la="./this.program",ma=(a,b)=>{throw b;},na="object"==typeof window,A="function"==typeof importScripts,C="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,D=z.ENVIRONMENT_IS_PTHREAD||!1,F="";function oa(a){return z.locateFile?z.locateFile(a,F):F+a}var pa,qa,ra;
if(C){var fs=require("fs"),sa=require("path");F=A?sa.dirname(F)+"/":__dirname+"/";pa=(b,d)=>{b=b.startsWith("file://")?new URL(b):sa.normalize(b);return fs.readFileSync(b,d?void 0:"utf8")};ra=b=>{b=pa(b,!0);b.buffer||(b=new Uint8Array(b));return b};qa=(b,d,e)=>{b=b.startsWith("file://")?new URL(b):sa.normalize(b);fs.readFile(b,function(f,g){f?e(f):d(g.buffer)})};1<process.argv.length&&(la=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);process.on("uncaughtException",function(b){if(!(b instanceof
ta))throw b;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",function(b){throw b;});ma=(b,d)=>{if(noExitRuntime)throw process.exitCode=b,d;if(!(d instanceof ta)){var e=d;d&&"object"==typeof d&&d.stack&&(e=[d,d.stack]);G("exiting due to exception: "+e)}process.exit(b)};z.inspect=function(){return"[Emscripten Module object]"};let a;try{a=require("worker_threads")}catch(b){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),
b;}global.Worker=a.Worker}else if(na||A)A?F=self.location.href:"undefined"!=typeof document&&document.currentScript&&(F=document.currentScript.src),_scriptDir&&(F=_scriptDir),0!==F.indexOf("blob:")?F=F.substr(0,F.replace(/[?#].*/,"").lastIndexOf("/")+1):F="",C||(pa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},A&&(ra=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),qa=(a,b,d)=>{var e=
new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):d()};e.onerror=d;e.send(null)});C&&"undefined"==typeof performance&&(global.performance=require("perf_hooks").performance);var ua=console.log.bind(console),va=console.warn.bind(console);C&&(ua=a=>fs.writeSync(1,a+"\n"),va=a=>fs.writeSync(2,a+"\n"));var wa=z.print||ua,G=z.printErr||va;Object.assign(z,ka);ka=null;z.thisProgram&&(la=z.thisProgram);z.quit&&(ma=z.quit);
var xa;z.wasmBinary&&(xa=z.wasmBinary);var noExitRuntime=z.noExitRuntime||!0;"object"!=typeof WebAssembly&&ya("no native wasm support detected");var h,za,Aa=!1,Ba="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ca(a,b,d){var e=b+d;for(d=b;a[d]&&!(d>=e);)++d;if(16<d-b&&a.buffer&&Ba)return Ba.decode(a.slice(b,d));for(e="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}function H(a,b){return a?Ca(r(),a,b):""}
function Da(a,b,d,e){if(!(0<e))return 0;var f=d;e=d+e-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var n=a.charCodeAt(++g);k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(d>=e)break;b[d++]=k}else{if(2047>=k){if(d+1>=e)break;b[d++]=192|k>>6}else{if(65535>=k){if(d+2>=e)break;b[d++]=224|k>>12}else{if(d+3>=e)break;b[d++]=240|k>>18;b[d++]=128|k>>12&63}b[d++]=128|k>>6&63}b[d++]=128|k&63}}b[d]=0;return d-f}function Ea(a,b,d){return Da(a,r(),b,d)}
function Fa(a){for(var b=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);127>=e?b++:2047>=e?b+=2:55296<=e&&57343>=e?(b+=4,++d):b+=3}return b}var m,aa,Ga,Ha,ba,ca,da,ha;function q(){var a=h.buffer;z.HEAP8=m=new Int8Array(a);z.HEAP16=Ga=new Int16Array(a);z.HEAP32=ba=new Int32Array(a);z.HEAPU8=aa=new Uint8Array(a);z.HEAPU16=Ha=new Uint16Array(a);z.HEAPU32=ca=new Uint32Array(a);z.HEAPF32=da=new Float32Array(a);z.HEAPF64=ha=new Float64Array(a)}var Ia=z.INITIAL_MEMORY||16777216;
65536<=Ia||ya("INITIAL_MEMORY should be larger than STACK_SIZE, was "+Ia+"! (STACK_SIZE=65536)");
if(D)h=z.wasmMemory;else if(z.wasmMemory)h=z.wasmMemory;else if(h=new WebAssembly.Memory({initial:Ia/65536,maximum:32768,shared:!0}),!(h.buffer instanceof SharedArrayBuffer))throw G("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),C&&G("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),
Error("bad memory");q();Ia=h.buffer.byteLength;var I,Ja=[],Ka=[],La=[];function Ma(){var a=z.preRun.shift();Ja.unshift(a)}var Na=0,Oa=null,Pa=null;function ya(a){if(z.onAbort)z.onAbort(a);a="Aborted("+a+")";G(a);Aa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ja(a);throw a;}function Qa(a){return a.startsWith("data:application/octet-stream;base64,")}var Ra;Ra="skwasm.wasm";Qa(Ra)||(Ra=oa(Ra));
function Sa(a){try{if(a==Ra&&xa)return new Uint8Array(xa);if(ra)return ra(a);throw"both async and sync fetching of the wasm failed";}catch(b){ya(b)}}
function Ta(a){if(!xa&&(na||A)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(function(){return Sa(a)});if(qa)return new Promise(function(b,d){qa(a,function(e){b(new Uint8Array(e))},d)})}return Promise.resolve().then(function(){return Sa(a)})}
function Ua(a,b,d){return Ta(a).then(function(e){return WebAssembly.instantiate(e,b)}).then(function(e){return e}).then(d,function(e){G("failed to asynchronously prepare wasm: "+e);ya(e)})}
function Va(a,b){var d=Ra;return xa||"function"!=typeof WebAssembly.instantiateStreaming||Qa(d)||d.startsWith("file://")||C||"function"!=typeof fetch?Ua(d,a,b):fetch(d,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,a).then(b,function(f){G("wasm streaming compile failed: "+f);G("falling back to ArrayBuffer instantiation");return Ua(d,a,b)})})}function ta(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function Wa(a){a.terminate();a.onmessage=()=>{}}function Xa(a){(a=J.o[a])||ya();J.ua(a)}function Ya(a){var b=J.ka();if(!b)return 6;J.v.push(b);J.o[a.h]=b;b.h=a.h;var d={cmd:"run",start_routine:a.wa,arg:a.ga,pthread_ptr:a.h};d.D=a.D;d.R=a.R;C&&b.ref();b.postMessage(d,a.Ca);return 0}function Za(a){if(D)return K(1,1,a);if(!noExitRuntime){J.xa();if(z.onExit)z.onExit(a);Aa=!0}ma(a,new ta(a))}function $a(a){if(D)throw ab(a),"unwind";Za(a)}
var J={s:[],v:[],da:[],o:{},P:function(){D?J.oa():J.na()},na:function(){for(var a=1;a--;)J.U()},oa:function(){J.receiveObjectTransfer=J.ta;J.threadInitTLS=J.ba;J.setExitStatus=J.aa;noExitRuntime=!1},aa:function(){},Ma:["$terminateWorker"],xa:function(){for(var a of J.v)Wa(a);for(a of J.s)Wa(a);J.s=[];J.v=[];J.o=[]},ua:function(a){var b=a.h;delete J.o[b];J.s.push(a);J.v.splice(J.v.indexOf(a),1);a.h=0;C&&a.unref();bb(b)},ta:function(a){"undefined"!=typeof cb&&(Object.assign(L,a.R),!z.canvas&&a.D&&L[a.D]&&
(z.canvas=L[a.D].u,z.canvas.id=a.D))},ba:function(){J.da.forEach(a=>a())},Y:a=>new Promise(b=>{a.onmessage=g=>{g=g.data;var k=g.cmd;a.h&&(J.ia=a.h);if(g.targetThread&&g.targetThread!=db()){var n=J.o[g.La];n?n.postMessage(g,g.transferList):G('Internal error! Worker sent a message "'+k+'" to target pthread '+g.targetThread+", but that thread no longer exists!")}else if("processProxyingQueue"===k)eb(g.queue);else if("spawnThread"===k)Ya(g);else if("cleanupThread"===k)Xa(g.thread);else if("killThread"===
k)g=g.thread,k=J.o[g],delete J.o[g],Wa(k),bb(g),J.v.splice(J.v.indexOf(k),1),k.h=0;else if("cancelThread"===k)J.o[g.thread].postMessage({cmd:"cancel"});else if("loaded"===k)a.loaded=!0,C&&!a.h&&a.unref(),b(a);else if("print"===k)wa("Thread "+g.threadId+": "+g.text);else if("printErr"===k)G("Thread "+g.threadId+": "+g.text);else if("alert"===k)alert("Thread "+g.threadId+": "+g.text);else if("setimmediate"===g.target)a.postMessage(g);else if("callHandler"===k)z[g.handler](...g.args);else k&&G("worker sent an unknown command "+
k);J.ia=void 0};a.onerror=g=>{G("worker sent an error! "+g.filename+":"+g.lineno+": "+g.message);throw g;};C&&(a.on("message",function(g){a.onmessage({data:g})}),a.on("error",function(g){a.onerror(g)}),a.on("detachedExit",function(){}));var d=[],e=["onExit","onAbort","print","printErr"],f;for(f of e)z.hasOwnProperty(f)&&d.push(f);a.postMessage({cmd:"load",handlers:d,urlOrBlob:z.mainScriptUrlOrBlob||_scriptDir,wasmMemory:h,wasmModule:za})}),qa:function(a){if(D)return a();Promise.all(J.s.map(J.Y)).then(a)},
U:function(){var a=oa("skwasm.worker.js");a=new Worker(a);J.s.push(a)},ka:function(){0==J.s.length&&(J.U(),J.Y(J.s[0]));return J.s.pop()}};z.PThread=J;function fb(a){for(;0<a.length;)a.shift()(z)}z.establishStackSpace=function(){var a=db(),b=u()[a+52>>2];a=u()[a+56>>2];gb(b,b-a);M(b)};function ab(a){if(D)return K(2,0,a);try{$a(a)}catch(b){b instanceof ta||"unwind"==b||ma(1,b)}}function N(a){return I.get(a)}z.invokeEntryPoint=function(a,b){a=N(a)(b);noExitRuntime?J.aa(a):hb(a)};
function ib(a){this.m=a-24;this.Da=function(b){w()[this.m+4>>2]=b};this.ra=function(b){w()[this.m+8>>2]=b};this.sa=function(){u()[this.m>>2]=0};this.pa=function(){var b=0;c()[this.m+12>>0]=b};this.va=function(){var b=0;c()[this.m+13>>0]=b};this.P=function(b,d){this.la();this.Da(b);this.ra(d);this.sa();this.pa();this.va()};this.la=function(){w()[this.m+16>>2]=0}}var jb=0;function kb(a,b,d,e){return D?K(3,1,a,b,d,e):lb(a,b,d,e)}
function lb(a,b,d,e){if("undefined"==typeof SharedArrayBuffer)return G("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var f=[],g=0,k=b?w()[b+40>>2]:0;4294967295==k?k="#canvas":k&&(k=H(k).trim());k&&(k=k.split(","));var n={},p=z.canvas?z.canvas.id:"",t;for(t in k){var v=k[t].trim();try{if("#canvas"==v){if(!z.canvas){G('pthread_create: could not find canvas with ID "'+v+'" to transfer to thread!');g=28;break}v=z.canvas.id}if(L[v]){var W=L[v];L[v]=null;z.canvas instanceof
OffscreenCanvas&&v===z.canvas.id&&(z.canvas=null)}else if(!D){var E=z.canvas&&z.canvas.id===v?z.canvas:document.querySelector(v);if(!E){G('pthread_create: could not find canvas with ID "'+v+'" to transfer to thread!');g=28;break}if(E.I){G('pthread_create: cannot transfer canvas with ID "'+v+'" to thread, since the current thread does not have control over it!');g=63;break}if(E.transferControlToOffscreen)E.g||(E.g=mb(12),u()[E.g>>2]=E.width,u()[E.g+4>>2]=E.height,u()[E.g+8>>2]=0),W={u:E.transferControlToOffscreen(),
g:E.g,id:E.id},E.I=!0;else return G('pthread_create: cannot transfer control of canvas "'+v+'" to pthread, because current browser does not support OffscreenCanvas!'),G("pthread_create: Build with -sOFFSCREEN_FRAMEBUFFER to enable fallback proxying of GL commands from pthread to main thread."),52}W&&(f.push(W.u),n[W.id]=W)}catch(l){return G('pthread_create: failed to transfer control of canvas "'+v+'" to OffscreenCanvas! Error: '+l),28}}if(D&&(0===f.length||g))return kb(a,b,d,e);if(g)return g;for(E of Object.values(n))u()[E.g+
8>>2]=a;a={wa:d,h:a,ga:e,D:p,R:n,Ca:f};return D?(a.Ea="spawnThread",postMessage(a,f),0):Ya(a)}function nb(a,b,d){return D?K(4,1,a,b,d):0}function ob(a,b){if(D)return K(5,1,a,b)}function pb(a,b,d){return D?K(6,1,a,b,d):0}function qb(a,b){if(D)return K(7,1,a,b)}function rb(a,b,d,e){if(D)return K(8,1,a,b,d,e)}function sb(a,b,d,e){if(D)return K(9,1,a,b,d,e)}function tb(a,b){if(D)return K(10,1,a,b)}function eb(a){Atomics.store(u(),a>>2,1);db()&&ub(a);Atomics.compareExchange(u(),a>>2,1,0)}
z.executeNotifiedProxyingQueue=eb;function vb(a){var b=O();a=a();M(b);return a}function wb(a){var b=Fa(a)+1,d=mb(b);Ea(a,d,b);return d}function xb(a,b,d,e){vb(function(){var f=yb(12),g=0;b&&(g=wb(b));u()[f>>2]=g;u()[f+4>>2]=d;u()[f+8>>2]=e;zb(a,654311424,0,g,f)})}
function Ab(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(d,e){b.vertexAttribDivisorANGLE(d,e)},a.drawArraysInstanced=function(d,e,f,g){b.drawArraysInstancedANGLE(d,e,f,g)},a.drawElementsInstanced=function(d,e,f,g,k){b.drawElementsInstancedANGLE(d,e,f,g,k)})}
function Bb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(d){b.deleteVertexArrayOES(d)},a.bindVertexArray=function(d){b.bindVertexArrayOES(d)},a.isVertexArray=function(d){return b.isVertexArrayOES(d)})}function Cb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(d,e){b.drawBuffersWEBGL(d,e)})}
var Db=1,Eb=[],P=[],Fb=[],Gb=[],Hb=[],Q=[],R=[],Ib={},L={},Jb=[],Kb=[],Lb={},Mb={},Nb=4;function S(a){Ob||(Ob=a)}function Pb(a){for(var b=Db++,d=a.length;d<b;d++)a[d]=null;return b}function Qb(a,b){a.m||(a.m=a.getContext,a.getContext=function(e,f){f=a.m(e,f);return"webgl"==e==f instanceof WebGLRenderingContext?f:null});var d=1<b.Z?a.getContext("webgl2",b):a.getContext("webgl",b);return d?Rb(d,b):0}
function Rb(a,b){var d=mb(8);u()[d+4>>2]=db();var e={Ga:d,attributes:b,version:b.Z,F:a};a.canvas&&(a.canvas.H=e);Ib[d]=e;("undefined"==typeof b.X||b.X)&&Sb(e);return d}
function Sb(a){a||(a=T);if(!a.ma){a.ma=!0;var b=a.F;Ab(b);Bb(b);Cb(b);b.V=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.$=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.W=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.W)b.W=b.getExtension("EXT_disjoint_timer_query");b.Ia=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(d){d.includes("lose_context")||d.includes("debug")||b.getExtension(d)})}}
var cb={},Ob,T;function Tb(a){a=2<a?H(a):a;return L[a.substr(1)]||"canvas"==a&&Object.keys(L)[0]||"undefined"!=typeof document&&document.querySelector(a)}function Ub(a,b,d){var e=Tb(a);if(!e)return-4;e.g&&(u()[e.g>>2]=b,u()[e.g+4>>2]=d);if(e.u||!e.I)e.u&&(e=e.u),a=!1,e.H&&e.H.F&&(a=e.H.F.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===e.width&&a[3]===e.height),e.width=b,e.height=d,a&&e.H.F.viewport(0,0,b,d);else return e.g?(e=u()[e.g+8>>2],a=a?H(a):"",xb(e,a,b,d),1):-4;return 0}
function Vb(a,b,d){return D?K(11,1,a,b,d):Ub(a,b,d)}function Wb(a,b,d){return Tb(a)?Ub(a,b,d):Vb(a,b,d)}function Xb(a,b,d,e,f,g,k){return D?K(12,1,a,b,d,e,f,g,k):-52}function Yb(a,b,d,e,f,g){if(D)return K(13,1,a,b,d,e,f,g)}var Zb,$b;$b=C?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.timeOrigin+performance.now();var ac=[];function bc(a,b,d,e){for(var f=0;f<a;f++){var g=U[d](),k=g&&Pb(e);g?(g.name=k,e[k]=g):S(1282);u()[b+4*f>>2]=k}}
function cc(a,b,d){if(b){var e=void 0;switch(a){case 36346:e=1;break;case 36344:0!=d&&1!=d&&S(1280);return;case 34814:case 36345:e=0;break;case 34466:var f=U.getParameter(34467);e=f?f.length:0;break;case 33309:if(2>T.version){S(1282);return}e=2*(U.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>T.version){S(1280);return}e=33307==a?3:0}if(void 0===e)switch(f=U.getParameter(a),typeof f){case "number":e=f;break;case "boolean":e=f?1:0;break;case "string":S(1280);return;case "object":if(null===
f)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:e=0;break;default:S(1280);return}else{if(f instanceof Float32Array||f instanceof Uint32Array||f instanceof Int32Array||f instanceof Array){for(a=0;a<f.length;++a)switch(d){case 0:u()[b+4*a>>2]=f[a];break;case 2:y()[b+4*a>>2]=f[a];break;case 4:c()[b+a>>0]=f[a]?1:0}return}try{e=f.name|
0}catch(g){S(1280);G("GL_INVALID_ENUM in glGet"+d+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:S(1280);G("GL_INVALID_ENUM in glGet"+d+"v: Native code calling glGet"+d+"v("+a+") and it returns "+f+" of type "+typeof f+"!");return}switch(d){case 1:d=e;w()[b>>2]=d;w()[b+4>>2]=(d-w()[b>>2])/4294967296;break;case 0:u()[b>>2]=e;break;case 2:y()[b>>2]=e;break;case 4:c()[b>>0]=e?1:0}}else S(1281)}
function dc(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function ec(a){a-=5120;0==a?a=c():1==a?a=r():2==a?(h.buffer!=m.buffer&&q(),a=Ga):4==a?a=u():6==a?a=y():5==a||28922==a||28520==a||30779==a||30782==a?a=w():(h.buffer!=m.buffer&&q(),a=Ha);return a}function fc(a,b,d,e,f){a=ec(a);var g=31-Math.clz32(a.BYTES_PER_ELEMENT),k=Nb;return a.subarray(f>>g,f+e*(d*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<g)+k-1&-k)>>g)}
function V(a){var b=U.ha;if(b){var d=b.G[a];"number"==typeof d&&(b.G[a]=d=U.getUniformLocation(b,b.ea[a]+(0<d?"["+d+"]":"")));return d}S(1282)}var X=[],gc=[];function K(a,b){var d=arguments.length-2,e=arguments;return vb(()=>{for(var f=yb(8*d),g=f>>3,k=0;k<d;k++){var n=e[2+k];fa()[g+k]=n}return hc(a,d,f,b)})}var ic=[],jc=["default","low-power","high-performance"],kc={};
function lc(){if(!nc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:la||"./this.program"},b;for(b in kc)void 0===kc[b]?delete a[b]:a[b]=kc[b];var d=[];for(b in a)d.push(b+"="+a[b]);nc=d}return nc}var nc;
function oc(a,b){if(D)return K(14,1,a,b);var d=0;lc().forEach(function(e,f){var g=b+d;f=w()[a+4*f>>2]=g;for(g=0;g<e.length;++g)c()[f++>>0]=e.charCodeAt(g);c()[f>>0]=0;d+=e.length+1});return 0}function pc(a,b){if(D)return K(15,1,a,b);var d=lc();w()[a>>2]=d.length;var e=0;d.forEach(function(f){e+=f.length+1});w()[b>>2]=e;return 0}function qc(a){return D?K(16,1,a):52}function rc(a,b,d,e,f,g){return D?K(17,1,a,b,d,e,f,g):52}function sc(a,b,d,e){return D?K(18,1,a,b,d,e):52}
function tc(a,b,d,e,f){return D?K(19,1,a,b,d,e,f):70}var uc=[null,[],[]];function vc(a,b,d,e){if(D)return K(20,1,a,b,d,e);for(var f=0,g=0;g<d;g++){var k=w()[b>>2],n=w()[b+4>>2];b+=8;for(var p=0;p<n;p++){var t=r()[k+p],v=uc[a];0===t||10===t?((1===a?wa:G)(Ca(v,0)),v.length=0):v.push(t)}f+=n}w()[e>>2]=f;return 0}function wc(a){return 0===a%4&&(0!==a%100||0===a%400)}var xc=[31,29,31,30,31,30,31,31,30,31,30,31],yc=[31,28,31,30,31,30,31,31,30,31,30,31];
function zc(a){var b=Array(Fa(a)+1);Da(a,b,0,b.length);return b}function Ac(a,b){c().set(a,b)}
function Bc(a,b,d,e){function f(l,x,B){for(l="number"==typeof l?l.toString():l||"";l.length<x;)l=B[0]+l;return l}function g(l,x){return f(l,x,"0")}function k(l,x){function B(mc){return 0>mc?-1:0<mc?1:0}var ea;0===(ea=B(l.getFullYear()-x.getFullYear()))&&0===(ea=B(l.getMonth()-x.getMonth()))&&(ea=B(l.getDate()-x.getDate()));return ea}function n(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),
0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-1,11,31);case 6:return new Date(l.getFullYear()-1,11,30)}}function p(l){var x=l.A;for(l=new Date((new Date(l.B+1900,0,1)).getTime());0<x;){var B=l.getMonth(),ea=(wc(l.getFullYear())?xc:yc)[B];if(x>ea-l.getDate())x-=ea-l.getDate()+1,l.setDate(1),11>B?l.setMonth(B+1):(l.setMonth(0),l.setFullYear(l.getFullYear()+1));else{l.setDate(l.getDate()+x);break}}B=new Date(l.getFullYear()+1,0,4);x=n(new Date(l.getFullYear(),
0,4));B=n(B);return 0>=k(x,l)?0>=k(B,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}var t=u()[e+40>>2];e={Aa:u()[e>>2],za:u()[e+4>>2],M:u()[e+8>>2],S:u()[e+12>>2],N:u()[e+16>>2],B:u()[e+20>>2],l:u()[e+24>>2],A:u()[e+28>>2],Na:u()[e+32>>2],ya:u()[e+36>>2],Ba:t?H(t):""};d=H(d);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var v in t)d=d.replace(new RegExp(v,"g"),t[v]);var W="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),E="January February March April May June July August September October November December".split(" ");t={"%a":function(l){return W[l.l].substring(0,3)},"%A":function(l){return W[l.l]},"%b":function(l){return E[l.N].substring(0,
3)},"%B":function(l){return E[l.N]},"%C":function(l){return g((l.B+1900)/100|0,2)},"%d":function(l){return g(l.S,2)},"%e":function(l){return f(l.S,2," ")},"%g":function(l){return p(l).toString().substring(2)},"%G":function(l){return p(l)},"%H":function(l){return g(l.M,2)},"%I":function(l){l=l.M;0==l?l=12:12<l&&(l-=12);return g(l,2)},"%j":function(l){for(var x=0,B=0;B<=l.N-1;x+=(wc(l.B+1900)?xc:yc)[B++]);return g(l.S+x,3)},"%m":function(l){return g(l.N+1,2)},"%M":function(l){return g(l.za,2)},"%n":function(){return"\n"},
"%p":function(l){return 0<=l.M&&12>l.M?"AM":"PM"},"%S":function(l){return g(l.Aa,2)},"%t":function(){return"\t"},"%u":function(l){return l.l||7},"%U":function(l){return g(Math.floor((l.A+7-l.l)/7),2)},"%V":function(l){var x=Math.floor((l.A+7-(l.l+6)%7)/7);2>=(l.l+371-l.A-2)%7&&x++;if(x)53==x&&(B=(l.l+371-l.A)%7,4==B||3==B&&wc(l.B)||(x=1));else{x=52;var B=(l.l+7-l.A-1)%7;(4==B||5==B&&wc(l.B%400-1))&&x++}return g(x,2)},"%w":function(l){return l.l},"%W":function(l){return g(Math.floor((l.A+7-(l.l+6)%
7)/7),2)},"%y":function(l){return(l.B+1900).toString().substring(2)},"%Y":function(l){return l.B+1900},"%z":function(l){l=l.ya;var x=0<=l;l=Math.abs(l)/60;return(x?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":function(l){return l.Ba},"%%":function(){return"%"}};d=d.replace(/%%/g,"\x00\x00");for(v in t)d.includes(v)&&(d=d.replace(new RegExp(v,"g"),t[v](e)));d=d.replace(/\0\0/g,"%");v=zc(d);if(v.length>b)return 0;Ac(v,a);return v.length-1}var Cc=void 0,Dc=[];J.P();for(var U,Y=0;32>Y;++Y)ac.push(Array(Y));
var Ec=new Float32Array(288);for(Y=0;288>Y;++Y)X[Y]=Ec.subarray(0,Y+1);var Fc=new Int32Array(288);for(Y=0;288>Y;++Y)gc[Y]=Fc.subarray(0,Y+1);
var Gc=[null,Za,ab,kb,nb,ob,pb,qb,rb,sb,tb,Vb,Xb,Yb,oc,pc,qc,rc,sc,tc,vc],Xc={__cxa_throw:function(a,b,d){(new ib(a)).P(b,d);jb++;throw a;},__emscripten_init_main_thread_js:function(a){Hc(a,!A,1,!na);J.ba()},__emscripten_thread_cleanup:function(a){D?postMessage({cmd:"cleanupThread",thread:a}):Xa(a)},__pthread_create_js:lb,__syscall_fcntl64:nb,__syscall_fstat64:ob,__syscall_ioctl:pb,__syscall_lstat64:qb,__syscall_newfstatat:rb,__syscall_openat:sb,__syscall_stat64:tb,_emscripten_default_pthread_stack_size:function(){return 65536},
_emscripten_get_now_is_monotonic:function(){return!0},_emscripten_notify_task_queue:function(a,b,d,e){a==b?setTimeout(()=>eb(e)):D?postMessage({targetThread:a,cmd:"processProxyingQueue",queue:e}):(a=J.o[a])&&a.postMessage({cmd:"processProxyingQueue",queue:e})},_emscripten_set_offscreencanvas_size:Wb,_emscripten_throw_longjmp:function(){throw Infinity;},_mmap_js:Xb,_munmap_js:Yb,abort:function(){ya("")},emscripten_check_blocking_allowed:function(){if(!C&&!A){var a="Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread";
Zb||(Zb={});Zb[a]||(Zb[a]=1,C&&(a="warning: "+a),G(a))}},emscripten_get_now:$b,emscripten_glActiveTexture:function(a){U.activeTexture(a)},emscripten_glAttachShader:function(a,b){U.attachShader(P[a],Q[b])},emscripten_glBindAttribLocation:function(a,b,d){U.bindAttribLocation(P[a],b,H(d))},emscripten_glBindBuffer:function(a,b){35051==a?U.O=b:35052==a&&(U.C=b);U.bindBuffer(a,Eb[b])},emscripten_glBindFramebuffer:function(a,b){U.bindFramebuffer(a,Fb[b])},emscripten_glBindRenderbuffer:function(a,b){U.bindRenderbuffer(a,
Gb[b])},emscripten_glBindSampler:function(a,b){U.bindSampler(a,Jb[b])},emscripten_glBindTexture:function(a,b){U.bindTexture(a,Hb[b])},emscripten_glBindVertexArray:function(a){U.bindVertexArray(R[a])},emscripten_glBindVertexArrayOES:function(a){U.bindVertexArray(R[a])},emscripten_glBlendColor:function(a,b,d,e){U.blendColor(a,b,d,e)},emscripten_glBlendEquation:function(a){U.blendEquation(a)},emscripten_glBlendFunc:function(a,b){U.blendFunc(a,b)},emscripten_glBlitFramebuffer:function(a,b,d,e,f,g,k,n,
p,t){U.blitFramebuffer(a,b,d,e,f,g,k,n,p,t)},emscripten_glBufferData:function(a,b,d,e){2<=T.version?d&&b?U.bufferData(a,r(),e,d,b):U.bufferData(a,b,e):U.bufferData(a,d?r().subarray(d,d+b):b,e)},emscripten_glBufferSubData:function(a,b,d,e){2<=T.version?d&&U.bufferSubData(a,b,r(),e,d):U.bufferSubData(a,b,r().subarray(e,e+d))},emscripten_glCheckFramebufferStatus:function(a){return U.checkFramebufferStatus(a)},emscripten_glClear:function(a){U.clear(a)},emscripten_glClearColor:function(a,b,d,e){U.clearColor(a,
b,d,e)},emscripten_glClearStencil:function(a){U.clearStencil(a)},emscripten_glClientWaitSync:function(a,b,d,e){return U.clientWaitSync(Kb[a],b,(d>>>0)+4294967296*e)},emscripten_glColorMask:function(a,b,d,e){U.colorMask(!!a,!!b,!!d,!!e)},emscripten_glCompileShader:function(a){U.compileShader(Q[a])},emscripten_glCompressedTexImage2D:function(a,b,d,e,f,g,k,n){2<=T.version?U.C||!k?U.compressedTexImage2D(a,b,d,e,f,g,k,n):U.compressedTexImage2D(a,b,d,e,f,g,r(),n,k):U.compressedTexImage2D(a,b,d,e,f,g,n?
r().subarray(n,n+k):null)},emscripten_glCompressedTexSubImage2D:function(a,b,d,e,f,g,k,n,p){2<=T.version?U.C||!n?U.compressedTexSubImage2D(a,b,d,e,f,g,k,n,p):U.compressedTexSubImage2D(a,b,d,e,f,g,k,r(),p,n):U.compressedTexSubImage2D(a,b,d,e,f,g,k,p?r().subarray(p,p+n):null)},emscripten_glCopyBufferSubData:function(a,b,d,e,f){U.copyBufferSubData(a,b,d,e,f)},emscripten_glCopyTexSubImage2D:function(a,b,d,e,f,g,k,n){U.copyTexSubImage2D(a,b,d,e,f,g,k,n)},emscripten_glCreateProgram:function(){var a=Pb(P),
b=U.createProgram();b.name=a;b.L=b.J=b.K=0;b.T=1;P[a]=b;return a},emscripten_glCreateShader:function(a){var b=Pb(Q);Q[b]=U.createShader(a);return b},emscripten_glCullFace:function(a){U.cullFace(a)},emscripten_glDeleteBuffers:function(a,b){for(var d=0;d<a;d++){var e=u()[b+4*d>>2],f=Eb[e];f&&(U.deleteBuffer(f),f.name=0,Eb[e]=null,e==U.O&&(U.O=0),e==U.C&&(U.C=0))}},emscripten_glDeleteFramebuffers:function(a,b){for(var d=0;d<a;++d){var e=u()[b+4*d>>2],f=Fb[e];f&&(U.deleteFramebuffer(f),f.name=0,Fb[e]=
null)}},emscripten_glDeleteProgram:function(a){if(a){var b=P[a];b?(U.deleteProgram(b),b.name=0,P[a]=null):S(1281)}},emscripten_glDeleteRenderbuffers:function(a,b){for(var d=0;d<a;d++){var e=u()[b+4*d>>2],f=Gb[e];f&&(U.deleteRenderbuffer(f),f.name=0,Gb[e]=null)}},emscripten_glDeleteSamplers:function(a,b){for(var d=0;d<a;d++){var e=u()[b+4*d>>2],f=Jb[e];f&&(U.deleteSampler(f),f.name=0,Jb[e]=null)}},emscripten_glDeleteShader:function(a){if(a){var b=Q[a];b?(U.deleteShader(b),Q[a]=null):S(1281)}},emscripten_glDeleteSync:function(a){if(a){var b=
Kb[a];b?(U.deleteSync(b),b.name=0,Kb[a]=null):S(1281)}},emscripten_glDeleteTextures:function(a,b){for(var d=0;d<a;d++){var e=u()[b+4*d>>2],f=Hb[e];f&&(U.deleteTexture(f),f.name=0,Hb[e]=null)}},emscripten_glDeleteVertexArrays:function(a,b){for(var d=0;d<a;d++){var e=u()[b+4*d>>2];U.deleteVertexArray(R[e]);R[e]=null}},emscripten_glDeleteVertexArraysOES:function(a,b){for(var d=0;d<a;d++){var e=u()[b+4*d>>2];U.deleteVertexArray(R[e]);R[e]=null}},emscripten_glDepthMask:function(a){U.depthMask(!!a)},emscripten_glDisable:function(a){U.disable(a)},
emscripten_glDisableVertexAttribArray:function(a){U.disableVertexAttribArray(a)},emscripten_glDrawArrays:function(a,b,d){U.drawArrays(a,b,d)},emscripten_glDrawArraysInstanced:function(a,b,d,e){U.drawArraysInstanced(a,b,d,e)},emscripten_glDrawArraysInstancedBaseInstanceWEBGL:function(a,b,d,e,f){U.V.drawArraysInstancedBaseInstanceWEBGL(a,b,d,e,f)},emscripten_glDrawBuffers:function(a,b){for(var d=ac[a],e=0;e<a;e++)d[e]=u()[b+4*e>>2];U.drawBuffers(d)},emscripten_glDrawElements:function(a,b,d,e){U.drawElements(a,
b,d,e)},emscripten_glDrawElementsInstanced:function(a,b,d,e,f){U.drawElementsInstanced(a,b,d,e,f)},emscripten_glDrawElementsInstancedBaseVertexBaseInstanceWEBGL:function(a,b,d,e,f,g,k){U.V.drawElementsInstancedBaseVertexBaseInstanceWEBGL(a,b,d,e,f,g,k)},emscripten_glDrawRangeElements:function(a,b,d,e,f,g){U.drawElements(a,e,f,g)},emscripten_glEnable:function(a){U.enable(a)},emscripten_glEnableVertexAttribArray:function(a){U.enableVertexAttribArray(a)},emscripten_glFenceSync:function(a,b){return(a=
U.fenceSync(a,b))?(b=Pb(Kb),a.name=b,Kb[b]=a,b):0},emscripten_glFinish:function(){U.finish()},emscripten_glFlush:function(){U.flush()},emscripten_glFramebufferRenderbuffer:function(a,b,d,e){U.framebufferRenderbuffer(a,b,d,Gb[e])},emscripten_glFramebufferTexture2D:function(a,b,d,e,f){U.framebufferTexture2D(a,b,d,Hb[e],f)},emscripten_glFrontFace:function(a){U.frontFace(a)},emscripten_glGenBuffers:function(a,b){bc(a,b,"createBuffer",Eb)},emscripten_glGenFramebuffers:function(a,b){bc(a,b,"createFramebuffer",
Fb)},emscripten_glGenRenderbuffers:function(a,b){bc(a,b,"createRenderbuffer",Gb)},emscripten_glGenSamplers:function(a,b){bc(a,b,"createSampler",Jb)},emscripten_glGenTextures:function(a,b){bc(a,b,"createTexture",Hb)},emscripten_glGenVertexArrays:function(a,b){bc(a,b,"createVertexArray",R)},emscripten_glGenVertexArraysOES:function(a,b){bc(a,b,"createVertexArray",R)},emscripten_glGenerateMipmap:function(a){U.generateMipmap(a)},emscripten_glGetBufferParameteriv:function(a,b,d){d?u()[d>>2]=U.getBufferParameter(a,
b):S(1281)},emscripten_glGetError:function(){var a=U.getError()||Ob;Ob=0;return a},emscripten_glGetFloatv:function(a,b){cc(a,b,2)},emscripten_glGetFramebufferAttachmentParameteriv:function(a,b,d,e){a=U.getFramebufferAttachmentParameter(a,b,d);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u()[e>>2]=a},emscripten_glGetIntegerv:function(a,b){cc(a,b,0)},emscripten_glGetProgramInfoLog:function(a,b,d,e){a=U.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&e?Ea(a,
e,b):0;d&&(u()[d>>2]=b)},emscripten_glGetProgramiv:function(a,b,d){if(d)if(a>=Db)S(1281);else if(a=P[a],35716==b)a=U.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u()[d>>2]=a.length+1;else if(35719==b){if(!a.L)for(b=0;b<U.getProgramParameter(a,35718);++b)a.L=Math.max(a.L,U.getActiveUniform(a,b).name.length+1);u()[d>>2]=a.L}else if(35722==b){if(!a.J)for(b=0;b<U.getProgramParameter(a,35721);++b)a.J=Math.max(a.J,U.getActiveAttrib(a,b).name.length+1);u()[d>>2]=a.J}else if(35381==b){if(!a.K)for(b=
0;b<U.getProgramParameter(a,35382);++b)a.K=Math.max(a.K,U.getActiveUniformBlockName(a,b).length+1);u()[d>>2]=a.K}else u()[d>>2]=U.getProgramParameter(a,b);else S(1281)},emscripten_glGetRenderbufferParameteriv:function(a,b,d){d?u()[d>>2]=U.getRenderbufferParameter(a,b):S(1281)},emscripten_glGetShaderInfoLog:function(a,b,d,e){a=U.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&e?Ea(a,e,b):0;d&&(u()[d>>2]=b)},emscripten_glGetShaderPrecisionFormat:function(a,b,d,e){a=U.getShaderPrecisionFormat(a,
b);u()[d>>2]=a.rangeMin;u()[d+4>>2]=a.rangeMax;u()[e>>2]=a.precision},emscripten_glGetShaderiv:function(a,b,d){d?35716==b?(a=U.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),a=a?a.length+1:0,u()[d>>2]=a):35720==b?(a=(a=U.getShaderSource(Q[a]))?a.length+1:0,u()[d>>2]=a):u()[d>>2]=U.getShaderParameter(Q[a],b):S(1281)},emscripten_glGetString:function(a){var b=Lb[a];if(!b){switch(a){case 7939:b=U.getSupportedExtensions()||[];b=b.concat(b.map(function(e){return"GL_"+e}));b=wb(b.join(" "));break;
case 7936:case 7937:case 37445:case 37446:(b=U.getParameter(a))||S(1280);b=b&&wb(b);break;case 7938:b=U.getParameter(7938);b=2<=T.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=wb(b);break;case 35724:b=U.getParameter(35724);var d=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==d&&(3==d[1].length&&(d[1]+="0"),b="OpenGL ES GLSL ES "+d[1]+" ("+b+")");b=wb(b);break;default:S(1280)}Lb[a]=b}return b},emscripten_glGetStringi:function(a,b){if(2>T.version)return S(1282),0;var d=Mb[a];
if(d)return 0>b||b>=d.length?(S(1281),0):d[b];switch(a){case 7939:return d=U.getSupportedExtensions()||[],d=d.concat(d.map(function(e){return"GL_"+e})),d=d.map(function(e){return wb(e)}),d=Mb[a]=d,0>b||b>=d.length?(S(1281),0):d[b];default:return S(1280),0}},emscripten_glGetUniformLocation:function(a,b){b=H(b);if(a=P[a]){var d=a,e=d.G,f=d.fa,g;if(!e)for(d.G=e={},d.ea={},g=0;g<U.getProgramParameter(d,35718);++g){var k=U.getActiveUniform(d,g);var n=k.name;k=k.size;var p=dc(n);p=0<p?n.slice(0,p):n;var t=
d.T;d.T+=k;f[p]=[k,t];for(n=0;n<k;++n)e[t]=n,d.ea[t++]=p}d=a.G;e=0;f=b;g=dc(b);0<g&&(e=parseInt(b.slice(g+1))>>>0,f=b.slice(0,g));if((f=a.fa[f])&&e<f[0]&&(e+=f[1],d[e]=d[e]||U.getUniformLocation(a,b)))return e}else S(1281);return-1},emscripten_glInvalidateFramebuffer:function(a,b,d){for(var e=ac[b],f=0;f<b;f++)e[f]=u()[d+4*f>>2];U.invalidateFramebuffer(a,e)},emscripten_glInvalidateSubFramebuffer:function(a,b,d,e,f,g,k){for(var n=ac[b],p=0;p<b;p++)n[p]=u()[d+4*p>>2];U.invalidateSubFramebuffer(a,n,
e,f,g,k)},emscripten_glIsSync:function(a){return U.isSync(Kb[a])},emscripten_glIsTexture:function(a){return(a=Hb[a])?U.isTexture(a):0},emscripten_glLineWidth:function(a){U.lineWidth(a)},emscripten_glLinkProgram:function(a){a=P[a];U.linkProgram(a);a.G=0;a.fa={}},emscripten_glMultiDrawArraysInstancedBaseInstanceWEBGL:function(a,b,d,e,f,g){U.$.multiDrawArraysInstancedBaseInstanceWEBGL(a,u(),b>>2,u(),d>>2,u(),e>>2,w(),f>>2,g)},emscripten_glMultiDrawElementsInstancedBaseVertexBaseInstanceWEBGL:function(a,
b,d,e,f,g,k,n){U.$.multiDrawElementsInstancedBaseVertexBaseInstanceWEBGL(a,u(),b>>2,d,u(),e>>2,u(),f>>2,u(),g>>2,w(),k>>2,n)},emscripten_glPixelStorei:function(a,b){3317==a&&(Nb=b);U.pixelStorei(a,b)},emscripten_glReadBuffer:function(a){U.readBuffer(a)},emscripten_glReadPixels:function(a,b,d,e,f,g,k){if(2<=T.version)if(U.O)U.readPixels(a,b,d,e,f,g,k);else{var n=ec(g);U.readPixels(a,b,d,e,f,g,n,k>>31-Math.clz32(n.BYTES_PER_ELEMENT))}else(k=fc(g,f,d,e,k))?U.readPixels(a,b,d,e,f,g,k):S(1280)},emscripten_glRenderbufferStorage:function(a,
b,d,e){U.renderbufferStorage(a,b,d,e)},emscripten_glRenderbufferStorageMultisample:function(a,b,d,e,f){U.renderbufferStorageMultisample(a,b,d,e,f)},emscripten_glSamplerParameterf:function(a,b,d){U.samplerParameterf(Jb[a],b,d)},emscripten_glSamplerParameteri:function(a,b,d){U.samplerParameteri(Jb[a],b,d)},emscripten_glSamplerParameteriv:function(a,b,d){d=u()[d>>2];U.samplerParameteri(Jb[a],b,d)},emscripten_glScissor:function(a,b,d,e){U.scissor(a,b,d,e)},emscripten_glShaderSource:function(a,b,d,e){for(var f=
"",g=0;g<b;++g){var k=e?u()[e+4*g>>2]:-1;f+=H(u()[d+4*g>>2],0>k?void 0:k)}U.shaderSource(Q[a],f)},emscripten_glStencilFunc:function(a,b,d){U.stencilFunc(a,b,d)},emscripten_glStencilFuncSeparate:function(a,b,d,e){U.stencilFuncSeparate(a,b,d,e)},emscripten_glStencilMask:function(a){U.stencilMask(a)},emscripten_glStencilMaskSeparate:function(a,b){U.stencilMaskSeparate(a,b)},emscripten_glStencilOp:function(a,b,d){U.stencilOp(a,b,d)},emscripten_glStencilOpSeparate:function(a,b,d,e){U.stencilOpSeparate(a,
b,d,e)},emscripten_glTexImage2D:function(a,b,d,e,f,g,k,n,p){if(2<=T.version)if(U.C)U.texImage2D(a,b,d,e,f,g,k,n,p);else if(p){var t=ec(n);U.texImage2D(a,b,d,e,f,g,k,n,t,p>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else U.texImage2D(a,b,d,e,f,g,k,n,null);else U.texImage2D(a,b,d,e,f,g,k,n,p?fc(n,k,e,f,p):null)},emscripten_glTexParameterf:function(a,b,d){U.texParameterf(a,b,d)},emscripten_glTexParameterfv:function(a,b,d){d=y()[d>>2];U.texParameterf(a,b,d)},emscripten_glTexParameteri:function(a,b,d){U.texParameteri(a,
b,d)},emscripten_glTexParameteriv:function(a,b,d){d=u()[d>>2];U.texParameteri(a,b,d)},emscripten_glTexStorage2D:function(a,b,d,e,f){U.texStorage2D(a,b,d,e,f)},emscripten_glTexSubImage2D:function(a,b,d,e,f,g,k,n,p){if(2<=T.version)if(U.C)U.texSubImage2D(a,b,d,e,f,g,k,n,p);else if(p){var t=ec(n);U.texSubImage2D(a,b,d,e,f,g,k,n,t,p>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else U.texSubImage2D(a,b,d,e,f,g,k,n,null);else t=null,p&&(t=fc(n,k,f,g,p)),U.texSubImage2D(a,b,d,e,f,g,k,n,t)},emscripten_glUniform1f:function(a,
b){U.uniform1f(V(a),b)},emscripten_glUniform1fv:function(a,b,d){if(2<=T.version)b&&U.uniform1fv(V(a),y(),d>>2,b);else{if(288>=b)for(var e=X[b-1],f=0;f<b;++f)e[f]=y()[d+4*f>>2];else e=y().subarray(d>>2,d+4*b>>2);U.uniform1fv(V(a),e)}},emscripten_glUniform1i:function(a,b){U.uniform1i(V(a),b)},emscripten_glUniform1iv:function(a,b,d){if(2<=T.version)b&&U.uniform1iv(V(a),u(),d>>2,b);else{if(288>=b)for(var e=gc[b-1],f=0;f<b;++f)e[f]=u()[d+4*f>>2];else e=u().subarray(d>>2,d+4*b>>2);U.uniform1iv(V(a),e)}},
emscripten_glUniform2f:function(a,b,d){U.uniform2f(V(a),b,d)},emscripten_glUniform2fv:function(a,b,d){if(2<=T.version)b&&U.uniform2fv(V(a),y(),d>>2,2*b);else{if(144>=b)for(var e=X[2*b-1],f=0;f<2*b;f+=2)e[f]=y()[d+4*f>>2],e[f+1]=y()[d+(4*f+4)>>2];else e=y().subarray(d>>2,d+8*b>>2);U.uniform2fv(V(a),e)}},emscripten_glUniform2i:function(a,b,d){U.uniform2i(V(a),b,d)},emscripten_glUniform2iv:function(a,b,d){if(2<=T.version)b&&U.uniform2iv(V(a),u(),d>>2,2*b);else{if(144>=b)for(var e=gc[2*b-1],f=0;f<2*b;f+=
2)e[f]=u()[d+4*f>>2],e[f+1]=u()[d+(4*f+4)>>2];else e=u().subarray(d>>2,d+8*b>>2);U.uniform2iv(V(a),e)}},emscripten_glUniform3f:function(a,b,d,e){U.uniform3f(V(a),b,d,e)},emscripten_glUniform3fv:function(a,b,d){if(2<=T.version)b&&U.uniform3fv(V(a),y(),d>>2,3*b);else{if(96>=b)for(var e=X[3*b-1],f=0;f<3*b;f+=3)e[f]=y()[d+4*f>>2],e[f+1]=y()[d+(4*f+4)>>2],e[f+2]=y()[d+(4*f+8)>>2];else e=y().subarray(d>>2,d+12*b>>2);U.uniform3fv(V(a),e)}},emscripten_glUniform3i:function(a,b,d,e){U.uniform3i(V(a),b,d,e)},
emscripten_glUniform3iv:function(a,b,d){if(2<=T.version)b&&U.uniform3iv(V(a),u(),d>>2,3*b);else{if(96>=b)for(var e=gc[3*b-1],f=0;f<3*b;f+=3)e[f]=u()[d+4*f>>2],e[f+1]=u()[d+(4*f+4)>>2],e[f+2]=u()[d+(4*f+8)>>2];else e=u().subarray(d>>2,d+12*b>>2);U.uniform3iv(V(a),e)}},emscripten_glUniform4f:function(a,b,d,e,f){U.uniform4f(V(a),b,d,e,f)},emscripten_glUniform4fv:function(a,b,d){if(2<=T.version)b&&U.uniform4fv(V(a),y(),d>>2,4*b);else{if(72>=b){var e=X[4*b-1],f=y();d>>=2;for(var g=0;g<4*b;g+=4){var k=
d+g;e[g]=f[k];e[g+1]=f[k+1];e[g+2]=f[k+2];e[g+3]=f[k+3]}}else e=y().subarray(d>>2,d+16*b>>2);U.uniform4fv(V(a),e)}},emscripten_glUniform4i:function(a,b,d,e,f){U.uniform4i(V(a),b,d,e,f)},emscripten_glUniform4iv:function(a,b,d){if(2<=T.version)b&&U.uniform4iv(V(a),u(),d>>2,4*b);else{if(72>=b)for(var e=gc[4*b-1],f=0;f<4*b;f+=4)e[f]=u()[d+4*f>>2],e[f+1]=u()[d+(4*f+4)>>2],e[f+2]=u()[d+(4*f+8)>>2],e[f+3]=u()[d+(4*f+12)>>2];else e=u().subarray(d>>2,d+16*b>>2);U.uniform4iv(V(a),e)}},emscripten_glUniformMatrix2fv:function(a,
b,d,e){if(2<=T.version)b&&U.uniformMatrix2fv(V(a),!!d,y(),e>>2,4*b);else{if(72>=b)for(var f=X[4*b-1],g=0;g<4*b;g+=4)f[g]=y()[e+4*g>>2],f[g+1]=y()[e+(4*g+4)>>2],f[g+2]=y()[e+(4*g+8)>>2],f[g+3]=y()[e+(4*g+12)>>2];else f=y().subarray(e>>2,e+16*b>>2);U.uniformMatrix2fv(V(a),!!d,f)}},emscripten_glUniformMatrix3fv:function(a,b,d,e){if(2<=T.version)b&&U.uniformMatrix3fv(V(a),!!d,y(),e>>2,9*b);else{if(32>=b)for(var f=X[9*b-1],g=0;g<9*b;g+=9)f[g]=y()[e+4*g>>2],f[g+1]=y()[e+(4*g+4)>>2],f[g+2]=y()[e+(4*g+8)>>
2],f[g+3]=y()[e+(4*g+12)>>2],f[g+4]=y()[e+(4*g+16)>>2],f[g+5]=y()[e+(4*g+20)>>2],f[g+6]=y()[e+(4*g+24)>>2],f[g+7]=y()[e+(4*g+28)>>2],f[g+8]=y()[e+(4*g+32)>>2];else f=y().subarray(e>>2,e+36*b>>2);U.uniformMatrix3fv(V(a),!!d,f)}},emscripten_glUniformMatrix4fv:function(a,b,d,e){if(2<=T.version)b&&U.uniformMatrix4fv(V(a),!!d,y(),e>>2,16*b);else{if(18>=b){var f=X[16*b-1],g=y();e>>=2;for(var k=0;k<16*b;k+=16){var n=e+k;f[k]=g[n];f[k+1]=g[n+1];f[k+2]=g[n+2];f[k+3]=g[n+3];f[k+4]=g[n+4];f[k+5]=g[n+5];f[k+
6]=g[n+6];f[k+7]=g[n+7];f[k+8]=g[n+8];f[k+9]=g[n+9];f[k+10]=g[n+10];f[k+11]=g[n+11];f[k+12]=g[n+12];f[k+13]=g[n+13];f[k+14]=g[n+14];f[k+15]=g[n+15]}}else f=y().subarray(e>>2,e+64*b>>2);U.uniformMatrix4fv(V(a),!!d,f)}},emscripten_glUseProgram:function(a){a=P[a];U.useProgram(a);U.ha=a},emscripten_glVertexAttrib1f:function(a,b){U.vertexAttrib1f(a,b)},emscripten_glVertexAttrib2fv:function(a,b){U.vertexAttrib2f(a,y()[b>>2],y()[b+4>>2])},emscripten_glVertexAttrib3fv:function(a,b){U.vertexAttrib3f(a,y()[b>>
2],y()[b+4>>2],y()[b+8>>2])},emscripten_glVertexAttrib4fv:function(a,b){U.vertexAttrib4f(a,y()[b>>2],y()[b+4>>2],y()[b+8>>2],y()[b+12>>2])},emscripten_glVertexAttribDivisor:function(a,b){U.vertexAttribDivisor(a,b)},emscripten_glVertexAttribIPointer:function(a,b,d,e,f){U.vertexAttribIPointer(a,b,d,e,f)},emscripten_glVertexAttribPointer:function(a,b,d,e,f,g){U.vertexAttribPointer(a,b,d,!!e,f,g)},emscripten_glViewport:function(a,b,d,e){U.viewport(a,b,d,e)},emscripten_glWaitSync:function(a,b,d,e){U.waitSync(Kb[a],
b,(d>>>0)+4294967296*e)},emscripten_receive_on_main_thread_js:function(a,b,d){ic.length=b;d>>=3;for(var e=0;e<b;e++)ic[e]=fa()[d+e];return Gc[a].apply(null,ic)},emscripten_resize_heap:function(a){var b=r().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var d=1;4>=d;d*=2){var e=b*(1+.2/d);e=Math.min(e,a+100663296);var f=Math,g=f.min;e=Math.max(a,e);e+=(65536-e%65536)%65536;a:{var k=h.buffer;try{h.grow(g.call(f,2147483648,e)-k.byteLength+65535>>>16);q();var n=1;break a}catch(p){}n=void 0}if(n)return!0}return!1},
emscripten_set_canvas_element_size:Wb,emscripten_unwind_to_js_event_loop:function(){throw"unwind";},emscripten_webgl_create_context:function(a,b){b>>=2;var d=u()[b+6];b={alpha:!!u()[b],depth:!!u()[b+1],stencil:!!u()[b+2],antialias:!!u()[b+3],premultipliedAlpha:!!u()[b+4],preserveDrawingBuffer:!!u()[b+5],powerPreference:jc[d],failIfMajorPerformanceCaveat:!!u()[b+7],Z:u()[b+8],Ha:u()[b+9],X:u()[b+10],ja:u()[b+11],Ja:u()[b+12],Ka:u()[b+13]};a=Tb(a);if(!a)return 0;a.u&&(a=a.u);if(b.ja){if(!(a.transferControlToOffscreen||
"undefined"!=typeof OffscreenCanvas&&a instanceof OffscreenCanvas))return 0;if(a.transferControlToOffscreen){if(!a.I)L[a.id]={canvas:a.transferControlToOffscreen(),g:mb(12),id:a.id},a.I=!0;else if(!L[a.id])return 0;a=L[a.id]}}return Qb(a,b)},emscripten_webgl_init_context_attributes:function(a){for(var b=a>>2,d=0;14>d;++d)u()[b+d]=0;u()[b]=u()[b+1]=u()[b+3]=u()[b+4]=u()[b+8]=u()[b+10]=1;A&&(u()[a+48>>2]=1)},emscripten_webgl_make_context_current:function(a){T=Ib[a];z.Fa=U=T&&T.F;return!a||U?0:-5},environ_get:oc,
environ_sizes_get:pc,exit:$a,fd_close:qc,fd_pread:rc,fd_read:sc,fd_seek:tc,fd_write:vc,invoke_ii:Ic,invoke_iii:Jc,invoke_iiii:Kc,invoke_iiiii:Lc,invoke_iiiiii:Mc,invoke_iiiiiii:Nc,invoke_v:Oc,invoke_vi:Pc,invoke_vii:Qc,invoke_viii:Rc,invoke_viiii:Sc,invoke_viiiii:Tc,invoke_viiiiii:Uc,invoke_viiiiiii:Vc,invoke_viiiiiiii:Wc,memory:h||z.wasmMemory,strftime_l:function(a,b,d,e){return Bc(a,b,d,e)}};
(function(){function a(d,e){d=d.exports;z.asm=d;J.da.push(z.asm._emscripten_tls_init);I=z.asm.__indirect_function_table;Ka.unshift(z.asm.__wasm_call_ctors);za=e;J.qa(()=>{Na--;z.monitorRunDependencies&&z.monitorRunDependencies(Na);if(0==Na&&(null!==Oa&&(clearInterval(Oa),Oa=null),Pa)){var f=Pa;Pa=null;f()}});return d}var b={env:Xc,wasi_snapshot_preview1:Xc};Na++;z.monitorRunDependencies&&z.monitorRunDependencies(Na);if(z.instantiateWasm)try{return z.instantiateWasm(b,a)}catch(d){G("Module.instantiateWasm callback failed with error: "+
d),ja(d)}Va(b,function(d){a(d.instance,d.module)}).catch(ja);return{}})();z._canvas_destroy=function(){return(z._canvas_destroy=z.asm.canvas_destroy).apply(null,arguments)};z._canvas_saveLayer=function(){return(z._canvas_saveLayer=z.asm.canvas_saveLayer).apply(null,arguments)};z._canvas_save=function(){return(z._canvas_save=z.asm.canvas_save).apply(null,arguments)};z._canvas_restore=function(){return(z._canvas_restore=z.asm.canvas_restore).apply(null,arguments)};
z._canvas_restoreToCount=function(){return(z._canvas_restoreToCount=z.asm.canvas_restoreToCount).apply(null,arguments)};z._canvas_getSaveCount=function(){return(z._canvas_getSaveCount=z.asm.canvas_getSaveCount).apply(null,arguments)};z._canvas_translate=function(){return(z._canvas_translate=z.asm.canvas_translate).apply(null,arguments)};z._canvas_scale=function(){return(z._canvas_scale=z.asm.canvas_scale).apply(null,arguments)};
z._canvas_rotate=function(){return(z._canvas_rotate=z.asm.canvas_rotate).apply(null,arguments)};z._canvas_skew=function(){return(z._canvas_skew=z.asm.canvas_skew).apply(null,arguments)};z._canvas_transform=function(){return(z._canvas_transform=z.asm.canvas_transform).apply(null,arguments)};z._canvas_clipRect=function(){return(z._canvas_clipRect=z.asm.canvas_clipRect).apply(null,arguments)};z._canvas_clipRRect=function(){return(z._canvas_clipRRect=z.asm.canvas_clipRRect).apply(null,arguments)};
z._canvas_clipPath=function(){return(z._canvas_clipPath=z.asm.canvas_clipPath).apply(null,arguments)};z._canvas_drawColor=function(){return(z._canvas_drawColor=z.asm.canvas_drawColor).apply(null,arguments)};z._canvas_drawLine=function(){return(z._canvas_drawLine=z.asm.canvas_drawLine).apply(null,arguments)};z._canvas_drawPaint=function(){return(z._canvas_drawPaint=z.asm.canvas_drawPaint).apply(null,arguments)};
z._canvas_drawRect=function(){return(z._canvas_drawRect=z.asm.canvas_drawRect).apply(null,arguments)};z._canvas_drawRRect=function(){return(z._canvas_drawRRect=z.asm.canvas_drawRRect).apply(null,arguments)};z._canvas_drawDRRect=function(){return(z._canvas_drawDRRect=z.asm.canvas_drawDRRect).apply(null,arguments)};z._canvas_drawOval=function(){return(z._canvas_drawOval=z.asm.canvas_drawOval).apply(null,arguments)};
z._canvas_drawCircle=function(){return(z._canvas_drawCircle=z.asm.canvas_drawCircle).apply(null,arguments)};z._canvas_drawArc=function(){return(z._canvas_drawArc=z.asm.canvas_drawArc).apply(null,arguments)};z._canvas_drawPath=function(){return(z._canvas_drawPath=z.asm.canvas_drawPath).apply(null,arguments)};z._canvas_drawShadow=function(){return(z._canvas_drawShadow=z.asm.canvas_drawShadow).apply(null,arguments)};
z._canvas_drawParagraph=function(){return(z._canvas_drawParagraph=z.asm.canvas_drawParagraph).apply(null,arguments)};z._canvas_drawPicture=function(){return(z._canvas_drawPicture=z.asm.canvas_drawPicture).apply(null,arguments)};z._canvas_getTransform=function(){return(z._canvas_getTransform=z.asm.canvas_getTransform).apply(null,arguments)};z._canvas_getLocalClipBounds=function(){return(z._canvas_getLocalClipBounds=z.asm.canvas_getLocalClipBounds).apply(null,arguments)};
z._canvas_getDeviceClipBounds=function(){return(z._canvas_getDeviceClipBounds=z.asm.canvas_getDeviceClipBounds).apply(null,arguments)};z._contourMeasureIter_create=function(){return(z._contourMeasureIter_create=z.asm.contourMeasureIter_create).apply(null,arguments)};z._contourMeasureIter_next=function(){return(z._contourMeasureIter_next=z.asm.contourMeasureIter_next).apply(null,arguments)};
z._contourMeasure_dispose=function(){return(z._contourMeasure_dispose=z.asm.contourMeasure_dispose).apply(null,arguments)};z._contourMeasure_length=function(){return(z._contourMeasure_length=z.asm.contourMeasure_length).apply(null,arguments)};z._contourMeasure_isClosed=function(){return(z._contourMeasure_isClosed=z.asm.contourMeasure_isClosed).apply(null,arguments)};z._contourMeasure_getPosTan=function(){return(z._contourMeasure_getPosTan=z.asm.contourMeasure_getPosTan).apply(null,arguments)};
z._contourMeasure_getSegment=function(){return(z._contourMeasure_getSegment=z.asm.contourMeasure_getSegment).apply(null,arguments)};z._skData_create=function(){return(z._skData_create=z.asm.skData_create).apply(null,arguments)};z._skData_getPointer=function(){return(z._skData_getPointer=z.asm.skData_getPointer).apply(null,arguments)};z._skData_dispose=function(){return(z._skData_dispose=z.asm.skData_dispose).apply(null,arguments)};
z._fontCollection_create=function(){return(z._fontCollection_create=z.asm.fontCollection_create).apply(null,arguments)};z._fontCollection_dispose=function(){return(z._fontCollection_dispose=z.asm.fontCollection_dispose).apply(null,arguments)};z._typeface_create=function(){return(z._typeface_create=z.asm.typeface_create).apply(null,arguments)};z._typeface_dispose=function(){return(z._typeface_dispose=z.asm.typeface_dispose).apply(null,arguments)};
z._typefaces_filterCoveredCodePoints=function(){return(z._typefaces_filterCoveredCodePoints=z.asm.typefaces_filterCoveredCodePoints).apply(null,arguments)};z._fontCollection_registerTypeface=function(){return(z._fontCollection_registerTypeface=z.asm.fontCollection_registerTypeface).apply(null,arguments)};z._paint_create=function(){return(z._paint_create=z.asm.paint_create).apply(null,arguments)};z._paint_destroy=function(){return(z._paint_destroy=z.asm.paint_destroy).apply(null,arguments)};
z._paint_setBlendMode=function(){return(z._paint_setBlendMode=z.asm.paint_setBlendMode).apply(null,arguments)};z._paint_setStyle=function(){return(z._paint_setStyle=z.asm.paint_setStyle).apply(null,arguments)};z._paint_getStyle=function(){return(z._paint_getStyle=z.asm.paint_getStyle).apply(null,arguments)};z._paint_setStrokeWidth=function(){return(z._paint_setStrokeWidth=z.asm.paint_setStrokeWidth).apply(null,arguments)};
z._paint_getStrokeWidth=function(){return(z._paint_getStrokeWidth=z.asm.paint_getStrokeWidth).apply(null,arguments)};z._paint_setStrokeCap=function(){return(z._paint_setStrokeCap=z.asm.paint_setStrokeCap).apply(null,arguments)};z._paint_getStrokeCap=function(){return(z._paint_getStrokeCap=z.asm.paint_getStrokeCap).apply(null,arguments)};z._paint_setStrokeJoin=function(){return(z._paint_setStrokeJoin=z.asm.paint_setStrokeJoin).apply(null,arguments)};
z._paint_getStrokeJoin=function(){return(z._paint_getStrokeJoin=z.asm.paint_getStrokeJoin).apply(null,arguments)};z._paint_setAntiAlias=function(){return(z._paint_setAntiAlias=z.asm.paint_setAntiAlias).apply(null,arguments)};z._paint_getAntiAlias=function(){return(z._paint_getAntiAlias=z.asm.paint_getAntiAlias).apply(null,arguments)};z._paint_setColorInt=function(){return(z._paint_setColorInt=z.asm.paint_setColorInt).apply(null,arguments)};
z._paint_getColorInt=function(){return(z._paint_getColorInt=z.asm.paint_getColorInt).apply(null,arguments)};z._paint_setMiterLimit=function(){return(z._paint_setMiterLimit=z.asm.paint_setMiterLimit).apply(null,arguments)};z._paint_getMiterLImit=function(){return(z._paint_getMiterLImit=z.asm.paint_getMiterLImit).apply(null,arguments)};z._paint_setShader=function(){return(z._paint_setShader=z.asm.paint_setShader).apply(null,arguments)};
z._path_create=function(){return(z._path_create=z.asm.path_create).apply(null,arguments)};z._path_destroy=function(){return(z._path_destroy=z.asm.path_destroy).apply(null,arguments)};z._path_copy=function(){return(z._path_copy=z.asm.path_copy).apply(null,arguments)};z._path_setFillType=function(){return(z._path_setFillType=z.asm.path_setFillType).apply(null,arguments)};z._path_getFillType=function(){return(z._path_getFillType=z.asm.path_getFillType).apply(null,arguments)};
z._path_moveTo=function(){return(z._path_moveTo=z.asm.path_moveTo).apply(null,arguments)};z._path_relativeMoveTo=function(){return(z._path_relativeMoveTo=z.asm.path_relativeMoveTo).apply(null,arguments)};z._path_lineTo=function(){return(z._path_lineTo=z.asm.path_lineTo).apply(null,arguments)};z._path_relativeLineTo=function(){return(z._path_relativeLineTo=z.asm.path_relativeLineTo).apply(null,arguments)};
z._path_quadraticBezierTo=function(){return(z._path_quadraticBezierTo=z.asm.path_quadraticBezierTo).apply(null,arguments)};z._path_relativeQuadraticBezierTo=function(){return(z._path_relativeQuadraticBezierTo=z.asm.path_relativeQuadraticBezierTo).apply(null,arguments)};z._path_cubicTo=function(){return(z._path_cubicTo=z.asm.path_cubicTo).apply(null,arguments)};z._path_relativeCubicTo=function(){return(z._path_relativeCubicTo=z.asm.path_relativeCubicTo).apply(null,arguments)};
z._path_conicTo=function(){return(z._path_conicTo=z.asm.path_conicTo).apply(null,arguments)};z._path_relativeConicTo=function(){return(z._path_relativeConicTo=z.asm.path_relativeConicTo).apply(null,arguments)};z._path_arcToOval=function(){return(z._path_arcToOval=z.asm.path_arcToOval).apply(null,arguments)};z._path_arcToRotated=function(){return(z._path_arcToRotated=z.asm.path_arcToRotated).apply(null,arguments)};
z._path_relativeArcToRotated=function(){return(z._path_relativeArcToRotated=z.asm.path_relativeArcToRotated).apply(null,arguments)};z._path_addRect=function(){return(z._path_addRect=z.asm.path_addRect).apply(null,arguments)};z._path_addOval=function(){return(z._path_addOval=z.asm.path_addOval).apply(null,arguments)};z._path_addArc=function(){return(z._path_addArc=z.asm.path_addArc).apply(null,arguments)};z._path_addPolygon=function(){return(z._path_addPolygon=z.asm.path_addPolygon).apply(null,arguments)};
z._path_addRRect=function(){return(z._path_addRRect=z.asm.path_addRRect).apply(null,arguments)};z._path_addPath=function(){return(z._path_addPath=z.asm.path_addPath).apply(null,arguments)};z._path_close=function(){return(z._path_close=z.asm.path_close).apply(null,arguments)};z._path_reset=function(){return(z._path_reset=z.asm.path_reset).apply(null,arguments)};z._path_contains=function(){return(z._path_contains=z.asm.path_contains).apply(null,arguments)};
z._path_transform=function(){return(z._path_transform=z.asm.path_transform).apply(null,arguments)};z._path_getBounds=function(){return(z._path_getBounds=z.asm.path_getBounds).apply(null,arguments)};z._path_combine=function(){return(z._path_combine=z.asm.path_combine).apply(null,arguments)};z._pictureRecorder_create=function(){return(z._pictureRecorder_create=z.asm.pictureRecorder_create).apply(null,arguments)};
z._pictureRecorder_dispose=function(){return(z._pictureRecorder_dispose=z.asm.pictureRecorder_dispose).apply(null,arguments)};z._pictureRecorder_beginRecording=function(){return(z._pictureRecorder_beginRecording=z.asm.pictureRecorder_beginRecording).apply(null,arguments)};z._pictureRecorder_endRecording=function(){return(z._pictureRecorder_endRecording=z.asm.pictureRecorder_endRecording).apply(null,arguments)};
z._picture_getCullRect=function(){return(z._picture_getCullRect=z.asm.picture_getCullRect).apply(null,arguments)};z._picture_dispose=function(){return(z._picture_dispose=z.asm.picture_dispose).apply(null,arguments)};z._picture_approximateBytesUsed=function(){return(z._picture_approximateBytesUsed=z.asm.picture_approximateBytesUsed).apply(null,arguments)};z._shader_createLinearGradient=function(){return(z._shader_createLinearGradient=z.asm.shader_createLinearGradient).apply(null,arguments)};
z._shader_createRadialGradient=function(){return(z._shader_createRadialGradient=z.asm.shader_createRadialGradient).apply(null,arguments)};z._shader_createConicalGradient=function(){return(z._shader_createConicalGradient=z.asm.shader_createConicalGradient).apply(null,arguments)};z._shader_createSweepGradient=function(){return(z._shader_createSweepGradient=z.asm.shader_createSweepGradient).apply(null,arguments)};
z._shader_dispose=function(){return(z._shader_dispose=z.asm.shader_dispose).apply(null,arguments)};z._runtimeEffect_create=function(){return(z._runtimeEffect_create=z.asm.runtimeEffect_create).apply(null,arguments)};z._runtimeEffect_dispose=function(){return(z._runtimeEffect_dispose=z.asm.runtimeEffect_dispose).apply(null,arguments)};z._runtimeEffect_getUniformSize=function(){return(z._runtimeEffect_getUniformSize=z.asm.runtimeEffect_getUniformSize).apply(null,arguments)};
z._shader_createRuntimeEffectShader=function(){return(z._shader_createRuntimeEffectShader=z.asm.shader_createRuntimeEffectShader).apply(null,arguments)};z._skString_allocate=function(){return(z._skString_allocate=z.asm.skString_allocate).apply(null,arguments)};z._skString_getData=function(){return(z._skString_getData=z.asm.skString_getData).apply(null,arguments)};z._skString_free=function(){return(z._skString_free=z.asm.skString_free).apply(null,arguments)};
z._skString16_allocate=function(){return(z._skString16_allocate=z.asm.skString16_allocate).apply(null,arguments)};z._skString16_getData=function(){return(z._skString16_getData=z.asm.skString16_getData).apply(null,arguments)};z._skString16_free=function(){return(z._skString16_free=z.asm.skString16_free).apply(null,arguments)};z._surface_createFromCanvas=function(){return(z._surface_createFromCanvas=z.asm.surface_createFromCanvas).apply(null,arguments)};
z._surface_setOnRenderCallback=function(){return(z._surface_setOnRenderCallback=z.asm.surface_setOnRenderCallback).apply(null,arguments)};z._surface_destroy=function(){return(z._surface_destroy=z.asm.surface_destroy).apply(null,arguments)};z._surface_setCanvasSize=function(){return(z._surface_setCanvasSize=z.asm.surface_setCanvasSize).apply(null,arguments)};z._surface_renderPicture=function(){return(z._surface_renderPicture=z.asm.surface_renderPicture).apply(null,arguments)};
function zb(){return(zb=z.asm.emscripten_dispatch_to_thread_).apply(null,arguments)}z._lineMetrics_create=function(){return(z._lineMetrics_create=z.asm.lineMetrics_create).apply(null,arguments)};z._lineMetrics_dispose=function(){return(z._lineMetrics_dispose=z.asm.lineMetrics_dispose).apply(null,arguments)};z._lineMetrics_getHardBreak=function(){return(z._lineMetrics_getHardBreak=z.asm.lineMetrics_getHardBreak).apply(null,arguments)};
z._lineMetrics_getAscent=function(){return(z._lineMetrics_getAscent=z.asm.lineMetrics_getAscent).apply(null,arguments)};z._lineMetrics_getDescent=function(){return(z._lineMetrics_getDescent=z.asm.lineMetrics_getDescent).apply(null,arguments)};z._lineMetrics_getUnscaledAscent=function(){return(z._lineMetrics_getUnscaledAscent=z.asm.lineMetrics_getUnscaledAscent).apply(null,arguments)};z._lineMetrics_getHeight=function(){return(z._lineMetrics_getHeight=z.asm.lineMetrics_getHeight).apply(null,arguments)};
z._lineMetrics_getWidth=function(){return(z._lineMetrics_getWidth=z.asm.lineMetrics_getWidth).apply(null,arguments)};z._lineMetrics_getLeft=function(){return(z._lineMetrics_getLeft=z.asm.lineMetrics_getLeft).apply(null,arguments)};z._lineMetrics_getBaseline=function(){return(z._lineMetrics_getBaseline=z.asm.lineMetrics_getBaseline).apply(null,arguments)};z._lineMetrics_getLineNumber=function(){return(z._lineMetrics_getLineNumber=z.asm.lineMetrics_getLineNumber).apply(null,arguments)};
z._lineMetrics_getStartIndex=function(){return(z._lineMetrics_getStartIndex=z.asm.lineMetrics_getStartIndex).apply(null,arguments)};z._lineMetrics_getEndIndex=function(){return(z._lineMetrics_getEndIndex=z.asm.lineMetrics_getEndIndex).apply(null,arguments)};z._paragraph_dispose=function(){return(z._paragraph_dispose=z.asm.paragraph_dispose).apply(null,arguments)};z._paragraph_getWidth=function(){return(z._paragraph_getWidth=z.asm.paragraph_getWidth).apply(null,arguments)};
z._paragraph_getHeight=function(){return(z._paragraph_getHeight=z.asm.paragraph_getHeight).apply(null,arguments)};z._paragraph_getLongestLine=function(){return(z._paragraph_getLongestLine=z.asm.paragraph_getLongestLine).apply(null,arguments)};z._paragraph_getMinIntrinsicWidth=function(){return(z._paragraph_getMinIntrinsicWidth=z.asm.paragraph_getMinIntrinsicWidth).apply(null,arguments)};
z._paragraph_getMaxIntrinsicWidth=function(){return(z._paragraph_getMaxIntrinsicWidth=z.asm.paragraph_getMaxIntrinsicWidth).apply(null,arguments)};z._paragraph_getAlphabeticBaseline=function(){return(z._paragraph_getAlphabeticBaseline=z.asm.paragraph_getAlphabeticBaseline).apply(null,arguments)};z._paragraph_getIdeographicBaseline=function(){return(z._paragraph_getIdeographicBaseline=z.asm.paragraph_getIdeographicBaseline).apply(null,arguments)};
z._paragraph_getDidExceedMaxLines=function(){return(z._paragraph_getDidExceedMaxLines=z.asm.paragraph_getDidExceedMaxLines).apply(null,arguments)};z._paragraph_layout=function(){return(z._paragraph_layout=z.asm.paragraph_layout).apply(null,arguments)};z._paragraph_getPositionForOffset=function(){return(z._paragraph_getPositionForOffset=z.asm.paragraph_getPositionForOffset).apply(null,arguments)};
z._paragraph_getWordBoundary=function(){return(z._paragraph_getWordBoundary=z.asm.paragraph_getWordBoundary).apply(null,arguments)};z._paragraph_getLineCount=function(){return(z._paragraph_getLineCount=z.asm.paragraph_getLineCount).apply(null,arguments)};z._paragraph_getLineNumberAt=function(){return(z._paragraph_getLineNumberAt=z.asm.paragraph_getLineNumberAt).apply(null,arguments)};
z._paragraph_getLineMetricsAtIndex=function(){return(z._paragraph_getLineMetricsAtIndex=z.asm.paragraph_getLineMetricsAtIndex).apply(null,arguments)};z._textBoxList_dispose=function(){return(z._textBoxList_dispose=z.asm.textBoxList_dispose).apply(null,arguments)};z._textBoxList_getLength=function(){return(z._textBoxList_getLength=z.asm.textBoxList_getLength).apply(null,arguments)};
z._textBoxList_getBoxAtIndex=function(){return(z._textBoxList_getBoxAtIndex=z.asm.textBoxList_getBoxAtIndex).apply(null,arguments)};z._paragraph_getBoxesForRange=function(){return(z._paragraph_getBoxesForRange=z.asm.paragraph_getBoxesForRange).apply(null,arguments)};z._paragraph_getBoxesForPlaceholders=function(){return(z._paragraph_getBoxesForPlaceholders=z.asm.paragraph_getBoxesForPlaceholders).apply(null,arguments)};
z._paragraphBuilder_create=function(){return(z._paragraphBuilder_create=z.asm.paragraphBuilder_create).apply(null,arguments)};z._paragraphBuilder_dispose=function(){return(z._paragraphBuilder_dispose=z.asm.paragraphBuilder_dispose).apply(null,arguments)};z._paragraphBuilder_addPlaceholder=function(){return(z._paragraphBuilder_addPlaceholder=z.asm.paragraphBuilder_addPlaceholder).apply(null,arguments)};
z._paragraphBuilder_addText=function(){return(z._paragraphBuilder_addText=z.asm.paragraphBuilder_addText).apply(null,arguments)};z._paragraphBuilder_pushStyle=function(){return(z._paragraphBuilder_pushStyle=z.asm.paragraphBuilder_pushStyle).apply(null,arguments)};z._paragraphBuilder_pop=function(){return(z._paragraphBuilder_pop=z.asm.paragraphBuilder_pop).apply(null,arguments)};z._paragraphBuilder_build=function(){return(z._paragraphBuilder_build=z.asm.paragraphBuilder_build).apply(null,arguments)};
z._paragraphStyle_create=function(){return(z._paragraphStyle_create=z.asm.paragraphStyle_create).apply(null,arguments)};z._paragraphStyle_dispose=function(){return(z._paragraphStyle_dispose=z.asm.paragraphStyle_dispose).apply(null,arguments)};z._paragraphStyle_setTextAlign=function(){return(z._paragraphStyle_setTextAlign=z.asm.paragraphStyle_setTextAlign).apply(null,arguments)};
z._paragraphStyle_setTextDirection=function(){return(z._paragraphStyle_setTextDirection=z.asm.paragraphStyle_setTextDirection).apply(null,arguments)};z._paragraphStyle_setMaxLines=function(){return(z._paragraphStyle_setMaxLines=z.asm.paragraphStyle_setMaxLines).apply(null,arguments)};z._paragraphStyle_setHeight=function(){return(z._paragraphStyle_setHeight=z.asm.paragraphStyle_setHeight).apply(null,arguments)};
z._paragraphStyle_setTextHeightBehavior=function(){return(z._paragraphStyle_setTextHeightBehavior=z.asm.paragraphStyle_setTextHeightBehavior).apply(null,arguments)};z._paragraphStyle_setEllipsis=function(){return(z._paragraphStyle_setEllipsis=z.asm.paragraphStyle_setEllipsis).apply(null,arguments)};z._paragraphStyle_setStrutStyle=function(){return(z._paragraphStyle_setStrutStyle=z.asm.paragraphStyle_setStrutStyle).apply(null,arguments)};
z._paragraphStyle_setTextStyle=function(){return(z._paragraphStyle_setTextStyle=z.asm.paragraphStyle_setTextStyle).apply(null,arguments)};z._strutStyle_create=function(){return(z._strutStyle_create=z.asm.strutStyle_create).apply(null,arguments)};z._strutStyle_dispose=function(){return(z._strutStyle_dispose=z.asm.strutStyle_dispose).apply(null,arguments)};z._strutStyle_setFontFamilies=function(){return(z._strutStyle_setFontFamilies=z.asm.strutStyle_setFontFamilies).apply(null,arguments)};
z._strutStyle_setFontSize=function(){return(z._strutStyle_setFontSize=z.asm.strutStyle_setFontSize).apply(null,arguments)};z._strutStyle_setHeight=function(){return(z._strutStyle_setHeight=z.asm.strutStyle_setHeight).apply(null,arguments)};z._strutStyle_setHalfLeading=function(){return(z._strutStyle_setHalfLeading=z.asm.strutStyle_setHalfLeading).apply(null,arguments)};z._strutStyle_setLeading=function(){return(z._strutStyle_setLeading=z.asm.strutStyle_setLeading).apply(null,arguments)};
z._strutStyle_setFontStyle=function(){return(z._strutStyle_setFontStyle=z.asm.strutStyle_setFontStyle).apply(null,arguments)};z._strutStyle_setForceStrutHeight=function(){return(z._strutStyle_setForceStrutHeight=z.asm.strutStyle_setForceStrutHeight).apply(null,arguments)};z._textStyle_create=function(){return(z._textStyle_create=z.asm.textStyle_create).apply(null,arguments)};z._textStyle_copy=function(){return(z._textStyle_copy=z.asm.textStyle_copy).apply(null,arguments)};
z._textStyle_dispose=function(){return(z._textStyle_dispose=z.asm.textStyle_dispose).apply(null,arguments)};z._textStyle_setColor=function(){return(z._textStyle_setColor=z.asm.textStyle_setColor).apply(null,arguments)};z._textStyle_setDecoration=function(){return(z._textStyle_setDecoration=z.asm.textStyle_setDecoration).apply(null,arguments)};z._textStyle_setDecorationColor=function(){return(z._textStyle_setDecorationColor=z.asm.textStyle_setDecorationColor).apply(null,arguments)};
z._textStyle_setDecorationStyle=function(){return(z._textStyle_setDecorationStyle=z.asm.textStyle_setDecorationStyle).apply(null,arguments)};z._textStyle_setDecorationThickness=function(){return(z._textStyle_setDecorationThickness=z.asm.textStyle_setDecorationThickness).apply(null,arguments)};z._textStyle_setFontStyle=function(){return(z._textStyle_setFontStyle=z.asm.textStyle_setFontStyle).apply(null,arguments)};
z._textStyle_setTextBaseline=function(){return(z._textStyle_setTextBaseline=z.asm.textStyle_setTextBaseline).apply(null,arguments)};z._textStyle_clearFontFamilies=function(){return(z._textStyle_clearFontFamilies=z.asm.textStyle_clearFontFamilies).apply(null,arguments)};z._textStyle_addFontFamilies=function(){return(z._textStyle_addFontFamilies=z.asm.textStyle_addFontFamilies).apply(null,arguments)};
z._textStyle_setFontSize=function(){return(z._textStyle_setFontSize=z.asm.textStyle_setFontSize).apply(null,arguments)};z._textStyle_setLetterSpacing=function(){return(z._textStyle_setLetterSpacing=z.asm.textStyle_setLetterSpacing).apply(null,arguments)};z._textStyle_setWordSpacing=function(){return(z._textStyle_setWordSpacing=z.asm.textStyle_setWordSpacing).apply(null,arguments)};z._textStyle_setHeight=function(){return(z._textStyle_setHeight=z.asm.textStyle_setHeight).apply(null,arguments)};
z._textStyle_setHalfLeading=function(){return(z._textStyle_setHalfLeading=z.asm.textStyle_setHalfLeading).apply(null,arguments)};z._textStyle_setLocale=function(){return(z._textStyle_setLocale=z.asm.textStyle_setLocale).apply(null,arguments)};z._textStyle_setBackground=function(){return(z._textStyle_setBackground=z.asm.textStyle_setBackground).apply(null,arguments)};z._textStyle_setForeground=function(){return(z._textStyle_setForeground=z.asm.textStyle_setForeground).apply(null,arguments)};
z._textStyle_addShadow=function(){return(z._textStyle_addShadow=z.asm.textStyle_addShadow).apply(null,arguments)};z._textStyle_addFontFeature=function(){return(z._textStyle_addFontFeature=z.asm.textStyle_addFontFeature).apply(null,arguments)};z._textStyle_setFontVariations=function(){return(z._textStyle_setFontVariations=z.asm.textStyle_setFontVariations).apply(null,arguments)};var db=z._pthread_self=function(){return(db=z._pthread_self=z.asm.pthread_self).apply(null,arguments)};
function mb(){return(mb=z.asm.malloc).apply(null,arguments)}z.__emscripten_tls_init=function(){return(z.__emscripten_tls_init=z.asm._emscripten_tls_init).apply(null,arguments)};var Hc=z.__emscripten_thread_init=function(){return(Hc=z.__emscripten_thread_init=z.asm._emscripten_thread_init).apply(null,arguments)};z.__emscripten_thread_crashed=function(){return(z.__emscripten_thread_crashed=z.asm._emscripten_thread_crashed).apply(null,arguments)};
function hc(){return(hc=z.asm._emscripten_run_in_main_runtime_thread_js).apply(null,arguments)}var ub=z.__emscripten_proxy_execute_task_queue=function(){return(ub=z.__emscripten_proxy_execute_task_queue=z.asm._emscripten_proxy_execute_task_queue).apply(null,arguments)};function bb(){return(bb=z.asm._emscripten_thread_free_data).apply(null,arguments)}var hb=z.__emscripten_thread_exit=function(){return(hb=z.__emscripten_thread_exit=z.asm._emscripten_thread_exit).apply(null,arguments)};
function Z(){return(Z=z.asm.setThrew).apply(null,arguments)}function gb(){return(gb=z.asm.emscripten_stack_set_limits).apply(null,arguments)}function O(){return(O=z.asm.stackSave).apply(null,arguments)}function M(){return(M=z.asm.stackRestore).apply(null,arguments)}var yb=z.stackAlloc=function(){return(yb=z.stackAlloc=z.asm.stackAlloc).apply(null,arguments)};function Qc(a,b,d){var e=O();try{N(a)(b,d)}catch(f){M(e);if(f!==f+0)throw f;Z(1,0)}}
function Wc(a,b,d,e,f,g,k,n,p){var t=O();try{N(a)(b,d,e,f,g,k,n,p)}catch(v){M(t);if(v!==v+0)throw v;Z(1,0)}}function Jc(a,b,d){var e=O();try{return N(a)(b,d)}catch(f){M(e);if(f!==f+0)throw f;Z(1,0)}}function Oc(a){var b=O();try{N(a)()}catch(d){M(b);if(d!==d+0)throw d;Z(1,0)}}function Ic(a,b){var d=O();try{return N(a)(b)}catch(e){M(d);if(e!==e+0)throw e;Z(1,0)}}function Pc(a,b){var d=O();try{N(a)(b)}catch(e){M(d);if(e!==e+0)throw e;Z(1,0)}}
function Lc(a,b,d,e,f){var g=O();try{return N(a)(b,d,e,f)}catch(k){M(g);if(k!==k+0)throw k;Z(1,0)}}function Kc(a,b,d,e){var f=O();try{return N(a)(b,d,e)}catch(g){M(f);if(g!==g+0)throw g;Z(1,0)}}function Rc(a,b,d,e){var f=O();try{N(a)(b,d,e)}catch(g){M(f);if(g!==g+0)throw g;Z(1,0)}}function Tc(a,b,d,e,f,g){var k=O();try{N(a)(b,d,e,f,g)}catch(n){M(k);if(n!==n+0)throw n;Z(1,0)}}function Nc(a,b,d,e,f,g,k){var n=O();try{return N(a)(b,d,e,f,g,k)}catch(p){M(n);if(p!==p+0)throw p;Z(1,0)}}
function Mc(a,b,d,e,f,g){var k=O();try{return N(a)(b,d,e,f,g)}catch(n){M(k);if(n!==n+0)throw n;Z(1,0)}}function Sc(a,b,d,e,f){var g=O();try{N(a)(b,d,e,f)}catch(k){M(g);if(k!==k+0)throw k;Z(1,0)}}function Uc(a,b,d,e,f,g,k){var n=O();try{N(a)(b,d,e,f,g,k)}catch(p){M(n);if(p!==p+0)throw p;Z(1,0)}}function Vc(a,b,d,e,f,g,k,n){var p=O();try{N(a)(b,d,e,f,g,k,n)}catch(t){M(p);if(t!==t+0)throw t;Z(1,0)}}z.keepRuntimeAlive=function(){return noExitRuntime};z.wasmMemory=h;
z.addFunction=function(a,b){if(!Cc){Cc=new WeakMap;var d=I.length;if(Cc)for(var e=0;e<0+d;e++){var f=N(e);f&&Cc.set(f,e)}}if(d=Cc.get(a)||0)return d;if(Dc.length)d=Dc.pop();else{try{I.grow(1)}catch(n){if(!(n instanceof RangeError))throw n;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}d=I.length-1}try{I.set(d,a)}catch(n){if(!(n instanceof TypeError))throw n;if("function"==typeof WebAssembly.Function){e=WebAssembly.Function;f={i:"i32",j:"i32",f:"f32",d:"f64",p:"i32"};for(var g={parameters:[],
results:"v"==b[0]?[]:[f[b[0]]]},k=1;k<b.length;++k)g.parameters.push(f[b[k]]),"j"===b[k]&&g.parameters.push("i32");b=new e(g,a)}else{e=[1];f=b.slice(0,1);b=b.slice(1);g={i:127,p:127,j:126,f:125,d:124};e.push(96);k=b.length;128>k?e.push(k):e.push(k%128|128,k>>7);for(k=0;k<b.length;++k)e.push(g[b[k]]);"v"==f?e.push(0):e.push(1,g[f]);b=[0,97,115,109,1,0,0,0,1];f=e.length;128>f?b.push(f):b.push(f%128|128,f>>7);b.push.apply(b,e);b.push(2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(new Uint8Array(b));
b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f}I.set(d,b)}Cc.set(a,d);return d};z.removeFunction=function(a){Cc.delete(N(a));Dc.push(a)};z.ExitStatus=ta;z.PThread=J;var Yc;Pa=function Zc(){Yc||$c();Yc||(Pa=Zc)};
function $c(){function a(){if(!Yc&&(Yc=!0,z.calledRun=!0,!Aa)){D||fb(Ka);ia(z);if(z.onRuntimeInitialized)z.onRuntimeInitialized();if(!D){if(z.postRun)for("function"==typeof z.postRun&&(z.postRun=[z.postRun]);z.postRun.length;){var b=z.postRun.shift();La.unshift(b)}fb(La)}}}if(!(0<Na))if(D)ia(z),D||fb(Ka),startWorker(z);else{if(z.preRun)for("function"==typeof z.preRun&&(z.preRun=[z.preRun]);z.preRun.length;)Ma();fb(Ja);0<Na||(z.setStatus?(z.setStatus("Running..."),setTimeout(function(){setTimeout(function(){z.setStatus("")},
1);a()},1)):a())}}if(z.preInit)for("function"==typeof z.preInit&&(z.preInit=[z.preInit]);0<z.preInit.length;)z.preInit.pop()();$c();


  return skwasm.ready
}

);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = skwasm;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return skwasm; });
else if (typeof exports === 'object')
  exports["skwasm"] = skwasm;
