name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0"

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'master'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Check code formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze code
        run: dart analyze --fatal-infos

      - name: Run vote tests
        working-directory: vote
        run: dart test

      - name: Run vote_widgets tests
        working-directory: vote_widgets
        run: flutter test

      - name: Run vote_demo tests
        working-directory: vote_demo
        run: flutter test
